/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const appDevSidebar = require('./sidebars-appdev.js').appDevSidebar;
const gameDevSidebar = require('./sidebars-gamedev.js').gameDevSidebar;
const industrySolutionsSidebar = require('./sidebars-industry.js').industrySolutionsSidebar;
const experienceSuggestionsSidebar = require('./sidebars-experience-suggestions.js').experienceSuggestionsSidebar;
const testingSidebar = require('./sidebars-testing.js').testingSidebar;
const toolsSidebar = require('./sidebars-tools.js').toolsSidebar;
const aiAssistSidebar = require('./sidebars-tools.js').aiAssistSidebar;
const devecoTestingSidebar = require('./sidebars-tools.js').devecoTestingSidebar;
const cliToolsSidebar = require('./sidebars-tools.js').cliToolsSidebar;
const ohpmSidebar = require('./sidebars-tools.js').ohpmSidebar;
const cloudDevSidebar = require('./sidebars-tools.js').cloudDevSidebar;
const promotionSidebar = require('./sidebars-promotion.js').promotionSidebar;
const monetizationSidebar = require('./sidebars-monetization.js').monetizationSidebar;
const releaseNotesSidebar = require('./sidebars-releases.js').releaseNotesSidebar;
const faqSidebar = require('./sidebars-faq.js').faqSidebar;
const contentDistSidebar = require('./sidebars-content-dist.js').contentDistSidebar;
const serviceDistSidebar = require('./sidebars-service-dist.js').serviceDistSidebar;
const appDistSidebar = require('./sidebars-app-dist.js').appDistSidebar;
const atomicSidebar = require('./sidebars-atomic.js').atomicSidebar;
const agcSidebarFull = require('./sidebars-agc.js').agcSidebar;
const xiaoyiSidebar = require('./sidebars-xiaoyi.js').xiaoyiSidebar;
const ndkDevSidebar = require('./sidebars-ndk.js').ndkDevSidebar;
const designSidebar = require('./sidebars-design.js').designSidebar;
const appCompatibilitySidebar = require('./sidebars-compatibility.js').appCompatibilitySidebar;
const qualitySidebar = require('./sidebars-quality.js').qualitySidebar;

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  appDevSidebar,
  atomicSidebar,
  ndkDevSidebar,
  gameDevSidebar,
  industrySolutionsSidebar,
  experienceSuggestionsSidebar,
  testingSidebar,
  faqSidebar: [
    'dev/faq/overview',
  ],
  designSidebar,
  appCompatibilitySidebar,
  toolsSidebar,
  aiAssistSidebar,
  devecoTestingSidebar,
  cliToolsSidebar,
  ohpmSidebar,
  cloudDevSidebar,
  
  architectureSidebar: [
    'architecture/overview',
    'architecture/layered',
    'architecture/modular',
  ],
  qualitySidebar,
  securitySidebar: [
    'security/app-privacy-protection',
    'security/app-data-security',
    'security/harmony-application-security',
    'security/app-asset-protection-design',
    'security/app-code-ob',
    'security/permission-application',
    'security/network-ca-security',
    'security/cross-platform-compatibility',
    'security/recommended-use-of-device-id',
    'security/arkweb-component-security',
  ],
  agcSidebarFull,
  xiaoyiSidebar,
  appDistSidebar,
  serviceDistSidebar,
  contentDistSidebar,
  designResSidebar: [
    'resources/design-res/overview',
    'resources/design-res/harmonyos-symbol',
  ],
  sampleCodeSidebar: [
    'resources/sample-code/overview',
    'resources/sample-code/sample-codes',
    'resources/sample-code/harmonyos-code-workshop',
  ],
  templatesSdkSidebar: [
    'resources/templates-sdk/templates',
    'resources/templates-sdk/components',
    'resources/templates-sdk/sdk-libs',
  ],
  crossPlatformSidebar: [
    'resources/cross-platform/overview',
  ],
  promotionSidebar,
  monetizationSidebar,
   
  releaseNotesSidebar,
  faqSidebar,
};

module.exports = sidebars;
