/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const atomicSidebar = [
  {
    type: 'category',
    label: '元服务开发',
    collapsed: false,
    items: [
      'dev/atomic-dev/overview',
      {
        type: 'category',
        label: '元服务概述',
        collapsed: true,
        items: [
          'dev/atomic-dev/atomic-service/atomic-service',
          'dev/atomic-dev/atomic-service/atomic-service-definition',
          'dev/atomic-dev/atomic-service/atomic-service-features',
          'dev/atomic-dev/atomic-service/atomic-service-package-basics',
        ],
      },
      'dev/atomic-dev/atomic-development-journey',
      {
        type: 'category',
        label: '开发第一个元服务',
        collapsed: true,
        items: [
          'dev/atomic-dev/develop-first-atomic-service/develop-first-atomic-service',
          'dev/atomic-dev/develop-first-atomic-service/atomic-service-start-overview',
          'dev/atomic-dev/develop-first-atomic-service/atomic-service-create-project',
          'dev/atomic-dev/develop-first-atomic-service/atomic-service-icon-generation',
          'dev/atomic-dev/develop-first-atomic-service/atomic-complete-default-widget',
          'dev/atomic-dev/develop-first-atomic-service/atomic-service-create-page',
          'dev/atomic-dev/develop-first-atomic-service/run-atomic-service',
        ],
      },
      {
        type: 'category',
        label: '元服务开发指导',
        collapsed: true,
        items: [
          'dev/atomic-dev/atomic-service-development/atomic-service-development',
          'dev/atomic-dev/atomic-service-development/atomic-dev-preparation',
          {
            type: 'category',
            label: '元服务框架开发',
            collapsed: true,
            items: [
              'dev/atomic-dev/atomic-service-framework-development/atomic-service-framework-development',
              {
                type: 'category',
                label: '分包加载',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-subpackage-loading/atomic-subpackage-loading',
                  'dev/atomic-dev/atomic-subpackage-loading/atomic-subcontract',
                  'dev/atomic-dev/atomic-subpackage-loading/atomic-preparing-for-loading',
                ],
              },
              {
                type: 'category',
                label: '跳转',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-service-routing/atomic-service-routing',
                  {
                    type: 'category',
                    label: 'Navigation路由跳转',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/atomic-navigation-routing/atomic-navigation-routing',
                      'dev/atomic-dev/atomic-navigation-routing/atomic-intra-module-page-routing',
                      'dev/atomic-dev/atomic-navigation-routing/atomic-inter-module-page-routing',
                    ],
                  },
                  {
                    type: 'category',
                    label: '使用App Linking跳转元服务',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/atomic-linking/atomic-linking',
                      'dev/atomic-dev/atomic-linking/atomic-applinking',
                      'dev/atomic-dev/atomic-linking/atomic-qrlinking',
                    ],
                  },
                ],
              },
              'dev/atomic-dev/atomic-service-framework-development/start-other-atomicservices',
              'dev/atomic-dev/atomic-service-framework-development/atomic-service-update',
            ],
          },
          {
            type: 'category',
            label: 'UI开发',
            collapsed: true,
            items: [
              'dev/atomic-dev/atomic-ui-development/atomic-ui-development',
              'dev/atomic-dev/atomic-ui-development/atomic-service-large-screen-adaptation',
            ],
          },
          'dev/atomic-dev/atomic-service-development/atomic-widget-development',
          {
            type: 'category',
            label: '基础能力开发',
            collapsed: true,
            items: [
              'dev/atomic-dev/atomic-basic-capability-development/atomic-basic-capability-development',
              {
                type: 'category',
                label: '网络',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-network-development/atomic-network-development',
                  'dev/atomic-dev/atomic-network-development/atomic-net-mgmt-overview',
                  'dev/atomic-dev/atomic-network-development/atomic-http-request',
                  'dev/atomic-dev/atomic-network-development/atomic-net-connection-manager',
                  'dev/atomic-dev/atomic-network-development/atomic-net-mdns',
                  'dev/atomic-dev/atomic-network-development/atomic-websocket-connection',
                  'dev/atomic-dev/atomic-network-development/agc-help-harmonyos-server-domain',
                ],
              },
              {
                type: 'category',
                label: '数据',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-database/atomic-database',
                  'dev/atomic-dev/atomic-database/atomic-data-persistence-by-preferences',
                ],
              },
              {
                type: 'category',
                label: '文件',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-file-development/atomic-file-development',
                  {
                    type: 'category',
                    label: '文件管理服务',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/atomic-file-management-service/atomic-file-management-service',
                      'dev/atomic-dev/atomic-file-management-service/atomic-app-file-access',
                    ],
                  },
                  'dev/atomic-dev/atomic-file-development/atomic-file-preview-service',
                ],
              },
              'dev/atomic-dev/atomic-basic-capability-development/atomic-audio-development',
              'dev/atomic-dev/atomic-basic-capability-development/atomic-avsession-development',
              'dev/atomic-dev/atomic-basic-capability-development/atomic-camera',
              {
                type: 'category',
                label: '媒体库',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-media-library-development/atomic-media-library-development',
                  'dev/atomic-dev/atomic-media-library-development/atomic-medialibrary-photoviewpicker',
                ],
              },
              {
                type: 'category',
                label: '图片',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-image-development/atomic-image-development',
                  'dev/atomic-dev/atomic-image-development/atomic-image-overview',
                  'dev/atomic-dev/atomic-image-development/atomic-image-decoding',
                  'dev/atomic-dev/atomic-image-development/atomic-image-encoding',
                ],
              },
              {
                type: 'category',
                label: '窗口',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-window-development/atomic-window-development',
                  'dev/atomic-dev/atomic-window-development/atomic-application-window',
                ],
              },
              {
                type: 'category',
                label: '设备管理',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-device-management/atomic-device-management',
                  'dev/atomic-dev/atomic-device-management/atomic-sensorservice-kit-intro',
                  {
                    type: 'category',
                    label: '传感器',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/atomic-sensor/atomic-sensor',
                      'dev/atomic-dev/atomic-sensor/atomic-sensor-overview',
                      'dev/atomic-dev/atomic-sensor/atomic-sensor-guidelines',
                    ],
                  },
                  {
                    type: 'category',
                    label: '振动',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/atomic-vibrator/atomic-vibrator',
                      'dev/atomic-dev/atomic-vibrator/atomic-vibrator-overview',
                      'dev/atomic-dev/atomic-vibrator/atomic-vibrator-guidelines',
                    ],
                  },
                ],
              },
              {
                type: 'category',
                label: '基础通信',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-connectivity/atomic-connectivity',
                  {
                    type: 'category',
                    label: '蓝牙',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/atomic-bluetooth/atomic-bluetooth',
                      'dev/atomic-dev/atomic-bluetooth/atomic-bluetooth-access',
                      'dev/atomic-dev/atomic-bluetooth/atomic-bluetooth-advertising',
                      'dev/atomic-dev/atomic-bluetooth/atomic-bluetooth-gatt',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'NFC',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/atomic-nfc/atomic-nfc',
                      'dev/atomic-dev/atomic-nfc/atomic-nfc-tag-access-guide',
                      'dev/atomic-dev/atomic-nfc/atomic-nfc-hce-guide',
                    ],
                  },
                ],
              },
              {
                type: 'category',
                label: '联系人',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-contacts/atomic-contacts',
                  'dev/atomic-dev/atomic-contacts/atomic-contacts-intro',
                ],
              },
              {
                type: 'category',
                label: 'Web',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-web-development/atomic-web-development',
                  'dev/atomic-dev/atomic-web-development/atomicserviceweb-guidelines',
                  'dev/atomic-dev/atomic-web-development/develop-atomicserviceenhancedweb',
                  'dev/atomic-dev/atomic-web-development/components-atomicserviceenhancedweb',
                  'dev/atomic-dev/atomic-web-development/web-upgraded-to-atomicserviceweb',
                  'dev/atomic-dev/atomic-web-development/agc-help-harmonyos-business-domain',
                ],
              },
              {
                type: 'category',
                label: 'AI能力',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-ai-development/atomic-ai-development',
                  'dev/atomic-dev/atomic-ai-development/atomic-vision-development',
                  'dev/atomic-dev/atomic-ai-development/atomic-intents-development',
                  'dev/atomic-dev/atomic-ai-development/atomic-agent-framework-development',
                ],
              },
              {
                type: 'category',
                label: '运动健康',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-health-service-development/atomic-health-service-development',
                  'dev/atomic-dev/atomic-health-service-development/health-service-kit-ability-as',
                  'dev/atomic-dev/atomic-health-service-development/health-application-access-as',
                  'dev/atomic-dev/atomic-health-service-development/health-application-qualifications-as',
                  {
                    type: 'category',
                    label: '开发接入',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/health-harmonyos-as/health-harmonyos-as',
                      'dev/atomic-dev/health-harmonyos-as/health-data-overview-as',
                      {
                        type: 'category',
                        label: '开发准备',
                        collapsed: true,
                        items: [
                          'dev/atomic-dev/health-preparations-as/health-preparations-as',
                          'dev/atomic-dev/health-preparations-as/health-apply-as',
                          'dev/atomic-dev/health-preparations-as/health-configuration-client-id-as',
                        ],
                      },
                      {
                        type: 'category',
                        label: '应用开发',
                        collapsed: true,
                        items: [
                          'dev/atomic-dev/health-app-dev-as/health-app-dev-as',
                          'dev/atomic-dev/health-app-dev-as/health-add-permissions-as',
                          'dev/atomic-dev/health-app-dev-as/health-samplepoint-manage-as',
                          'dev/atomic-dev/health-app-dev-as/health-three-ring-read-as',
                        ],
                      },
                      {
                        type: 'category',
                        label: '数据类型',
                        collapsed: true,
                        items: [
                          'dev/atomic-dev/health-data-type-as/health-data-type-as',
                          'dev/atomic-dev/health-data-type-as/health-permission-description-as',
                          {
                            type: 'category',
                            label: '采样数据',
                            collapsed: true,
                            items: [
                              'dev/atomic-dev/health-samplepoint-as/health-samplepoint-as',
                              'dev/atomic-dev/health-samplepoint-as/health-daily-activities-as',
                            ],
                          },
                        ],
                      },
                      'dev/atomic-dev/health-harmonyos-as/health-verification-as',
                      'dev/atomic-dev/health-harmonyos-as/health-personal-data-atomicservice-as',
                    ],
                  },
                  {
                    type: 'category',
                    label: '附录',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/health-appendix-as/health-appendix-as',
                      'dev/atomic-dev/health-appendix-as/health-logo-usage-regulations-as',
                    ],
                  },
                ],
              },
              'dev/atomic-dev/atomic-basic-capability-development/atomic-cloud-foundation-development',
              {
                type: 'category',
                label: '安全',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-security-development/atomic-security-development',
                  'dev/atomic-dev/atomic-security-development/atomic-huks-guidelines',
                  'dev/atomic-dev/atomic-security-development/atomic-online-auth-development',
                  'dev/atomic-dev/atomic-security-development/atomic-cryptoframework-guidelines',
                  'dev/atomic-dev/atomic-security-development/atomic-cert-guidelines',
                  'dev/atomic-dev/atomic-security-development/atomic-user-authentication-guidelines',
                  {
                    type: 'category',
                    label: '设备安全',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/atomic-device-security-development/atomic-device-security-development',
                      'dev/atomic-dev/atomic-device-security-development/atomic-devicesecurity-introduction',
                      'dev/atomic-dev/atomic-device-security-development/atomic-devicesecurity-quota',
                      {
                        type: 'category',
                        label: '开发准备',
                        collapsed: true,
                        items: [
                          'dev/atomic-dev/atomic-devicesecurity-prepare/atomic-devicesecurity-prepare',
                          'dev/atomic-dev/atomic-devicesecurity-prepare/atomic-devicesecurity-deviceverify-activateservice',
                          'dev/atomic-dev/atomic-devicesecurity-prepare/atomic-devicesecurity-deviceverify-token',
                        ],
                      },
                      'dev/atomic-dev/atomic-device-security-development/atomic-devicesecurity-deviceverify-develop',
                      {
                        type: 'category',
                        label: '安全检测',
                        collapsed: true,
                        items: [
                          'dev/atomic-dev/atomic-devicesecurity-safetydetect-develop/atomic-devicesecurity-safetydetect-develop',
                          'dev/atomic-dev/atomic-devicesecurity-safetydetect-develop/atomic-devicesecurity-sysintegrityenhanced-check',
                          'dev/atomic-dev/atomic-devicesecurity-safetydetect-develop/atomic-devicesecurity-sysintegrity-check',
                          'dev/atomic-dev/atomic-devicesecurity-safetydetect-develop/atomic-devicesecurity-urlthreat-check',
                        ],
                      },
                      {
                        type: 'category',
                        label: '可信应用服务',
                        collapsed: true,
                        items: [
                          'dev/atomic-dev/atomic-devicesecurity-taas-dev/atomic-devicesecurity-taas-dev',
                          'dev/atomic-dev/atomic-devicesecurity-taas-dev/atomic-devicesecurity-taas-securelocation',
                          {
                            type: 'category',
                            label: '签名验证',
                            collapsed: true,
                            items: [
                              'dev/atomic-dev/atomic-devicesecurity-taas-verify/atomic-devicesecurity-taas-verify',
                              'dev/atomic-dev/atomic-devicesecurity-taas-verify/atomic-devicesecurity-taas-verifycertchain',
                              'dev/atomic-dev/atomic-devicesecurity-taas-verify/atomic-devicesecurity-taas-verifysignature',
                            ],
                          },
                        ],
                      },
                      {
                        type: 'category',
                        label: '附录',
                        collapsed: true,
                        items: [
                          'dev/atomic-dev/atomic-devicesecurity-appendix/atomic-devicesecurity-appendix',
                          'dev/atomic-dev/atomic-devicesecurity-appendix/atomic-devicesecurity-appendix-region',
                        ],
                      },
                    ],
                  },
                  {
                    type: 'category',
                    label: '内容风控服务',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/content-moderation-service/content-moderation-service',
                      'dev/atomic-dev/content-moderation-service/content-moderation-service-intro',
                      {
                        type: 'category',
                        label: '开发准备',
                        collapsed: true,
                        items: [
                          'dev/atomic-dev/content-moderation-service-prep/content-moderation-service-prep',
                          'dev/atomic-dev/content-moderation-service-prep/content-moderation-service-prep-enable',
                          'dev/atomic-dev/content-moderation-service-prep/content-moderation-service-prep-connector-create',
                        ],
                      },
                      'dev/atomic-dev/content-moderation-service/content-moderation-service-personal-data-proces',
                    ],
                  },
                ],
              },
              'dev/atomic-dev/atomic-basic-capability-development/atomic-weather-service-development',
              'dev/atomic-dev/atomic-basic-capability-development/atomic-localization',
              'dev/atomic-dev/atomic-basic-capability-development/atomic-backgroundtask',
              {
                type: 'category',
                label: '日志',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-log-development/atomic-log-development',
                  'dev/atomic-dev/atomic-log-development/atomic-hiappevent-guidelines',
                  'dev/atomic-dev/atomic-log-development/atomic-hilog-development',
                ],
              },
              'dev/atomic-dev/atomic-basic-capability-development/atomic-arkts-utils',
              'dev/atomic-dev/atomic-basic-capability-development/atomic-arkxtest-guidelines',
            ],
          },
          {
            type: 'category',
            label: '经营履约能力开发',
            collapsed: true,
            items: [
              'dev/atomic-dev/operations-fulfillment-capability-development/operations-fulfillment-capability-development',
              {
                type: 'category',
                label: '账号',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-account-development/atomic-account-development',
                  'dev/atomic-dev/atomic-account-development/account-guide-atomic-introduction',
                  'dev/atomic-dev/atomic-account-development/account-guide-atomic-detailedrules',
                  {
                    type: 'category',
                    label: '开发准备',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/account-guide-atomic-preparations/account-guide-atomic-preparations',
                      'dev/atomic-dev/account-guide-atomic-preparations/account-guide-atomic-permissions',
                      'dev/atomic-dev/account-guide-atomic-preparations/account-atomic-sign-fingerprints',
                      'dev/atomic-dev/account-guide-atomic-preparations/account-atomic-client-id',
                    ],
                  },
                  'dev/atomic-dev/atomic-account-development/account-atomic-silent-login',
                  {
                    type: 'category',
                    label: '获取华为账号用户信息',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/account-guide-atomic-get-user-info/account-guide-atomic-get-user-info',
                      'dev/atomic-dev/account-guide-atomic-get-user-info/account-guide-atomic-get-user-info-overview',
                      {
                        type: 'category',
                        label: '获取头像昵称',
                        collapsed: true,
                        items: [
                          'dev/atomic-dev/account-guide-atomic-get-avatar-nickname/account-guide-atomic-get-avatar-nickname',
                          'dev/atomic-dev/account-guide-atomic-get-avatar-nickname/account-guide-atomic-get-avatar-nickname-overview',
                          'dev/atomic-dev/account-guide-atomic-get-avatar-nickname/account-guide-atomic-get-avatar-nickname-api',
                          'dev/atomic-dev/account-guide-atomic-get-avatar-nickname/account-guide-atomic-get-avatar-nickname-button',
                        ],
                      },
                      {
                        type: 'category',
                        label: '获取手机号',
                        collapsed: true,
                        items: [
                          'dev/atomic-dev/account-guide-atomic-get-phone/account-guide-atomic-get-phone',
                          'dev/atomic-dev/account-guide-atomic-get-phone/account-guide-atomic-get-phone-overview',
                          'dev/atomic-dev/account-guide-atomic-get-phone/account-guide-atomic-get-phonenumber',
                        ],
                      },
                      'dev/atomic-dev/account-guide-atomic-get-user-info/account-guide-atomic-choose-address',
                      'dev/atomic-dev/account-guide-atomic-get-user-info/account-guide-atomic-select-invoice-title',
                      'dev/atomic-dev/account-guide-atomic-get-user-info/account-guide-atomic-get-risklevel',
                    ],
                  },
                  {
                    type: 'category',
                    label: '未成年人模式',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/account-guide-atomic-minorsprotection/account-guide-atomic-minorsprotection',
                      'dev/atomic-dev/account-guide-atomic-minorsprotection/account-guide-atomic-overview-minorsprotection',
                      {
                        type: 'category',
                        label: '元服务与系统实现未成年人模式联动',
                        collapsed: true,
                        items: [
                          'dev/atomic-dev/account-follow-atomic-minorsprotection/account-follow-atomic-minorsprotection',
                          'dev/atomic-dev/account-follow-atomic-minorsprotection/account-system-atomic-minorsprotection',
                          'dev/atomic-dev/account-follow-atomic-minorsprotection/account-atomic-turn-on-minorsprotection',
                          {
                            type: 'category',
                            label: '元服务内关闭未成年人模式',
                            collapsed: true,
                            items: [
                              'dev/atomic-dev/account-atomic-turn-off-minorsprotection/account-atomic-turn-off-minorsprotection',
                              'dev/atomic-dev/account-atomic-turn-off-minorsprotection/account-atomicself-turn-off-minorsprotection',
                              'dev/atomic-dev/account-atomic-turn-off-minorsprotection/account-system-turn-off-atomic-minorsprotection',
                            ],
                          },
                          'dev/atomic-dev/account-follow-atomic-minorsprotection/account-password-atomic-minorsprotection',
                        ],
                      },
                    ],
                  },
                  'dev/atomic-dev/atomic-account-development/account-guide-atomic-sub-pro-userinfo-change',
                  'dev/atomic-dev/atomic-account-development/account-guide-atomic-faq',
                  'dev/atomic-dev/atomic-account-development/account-atomic-personal-data',
                ],
              },
              {
                type: 'category',
                label: '推送',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-push-development/atomic-push-development',
                  'dev/atomic-dev/atomic-push-development/push-as-intro',
                  'dev/atomic-dev/atomic-push-development/push-as-prepare',
                  {
                    type: 'category',
                    label: '推送基于账号的服务通知订阅消息',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/push-as-subscription/push-as-subscription',
                      'dev/atomic-dev/push-as-subscription/push-as-service-noti',
                      'dev/atomic-dev/push-as-subscription/push-as-service-self',
                      'dev/atomic-dev/push-as-subscription/push-as-request-sub',
                      'dev/atomic-dev/push-as-subscription/push-as-send-sub-noti',
                    ],
                  },
                  'dev/atomic-dev/atomic-push-development/push-as-timeline',
                ],
              },
              'dev/atomic-dev/operations-fulfillment-capability-development/atomic-share-development',
              {
                type: 'category',
                label: '扫码',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-code-scan-development/atomic-code-scan-development',
                  'dev/atomic-dev/atomic-code-scan-development/atomic-scan-introduction',
                  'dev/atomic-dev/atomic-code-scan-development/atomic-scan-config-agc',
                  'dev/atomic-dev/atomic-code-scan-development/atomic-scan-default-mode',
                  {
                    type: 'category',
                    label: '码图生成',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/atomic-scan-generate/atomic-scan-generate',
                      'dev/atomic-dev/atomic-scan-generate/atomic-scan-barcodegenerate',
                      'dev/atomic-dev/atomic-scan-generate/atomic-scan-generatearray',
                    ],
                  },
                  'dev/atomic-dev/atomic-code-scan-development/atomic-scan-faq',
                ],
              },
              'dev/atomic-dev/operations-fulfillment-capability-development/atomic-location-development',
              'dev/atomic-dev/operations-fulfillment-capability-development/atomic-map-development',
              'dev/atomic-dev/operations-fulfillment-capability-development/atomic-payment-development',
              'dev/atomic-dev/operations-fulfillment-capability-development/atomic-iap-development',
              {
                type: 'category',
                label: '广告',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ads-kit-atomicservice/ads-kit-atomicservice',
                  'dev/atomic-dev/ads-kit-atomicservice/atomic-ads-introduction',
                  'dev/atomic-dev/ads-kit-atomicservice/development-preparation',
                  {
                    type: 'category',
                    label: '流量变现服务开发',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/atomic-ads-publisher-service-dev/atomic-ads-publisher-service-dev',
                      'dev/atomic-dev/atomic-ads-publisher-service-dev/atomic-ads-publisher-service-dev-overview',
                      'dev/atomic-dev/atomic-ads-publisher-service-dev/atomic-ads-publisher-service-banner',
                      'dev/atomic-dev/atomic-ads-publisher-service-dev/atomic-ads-publisher-service-native',
                      'dev/atomic-dev/atomic-ads-publisher-service-dev/atomic-ads-publisher-service-reward',
                      'dev/atomic-dev/atomic-ads-publisher-service-dev/atomic-ads-publisher-service-interstitial',
                      'dev/atomic-dev/atomic-ads-publisher-service-dev/atomic-ads-publisher-service-roll',
                      'dev/atomic-dev/atomic-ads-publisher-service-dev/metaservice-ads-real-time-bidding',
                      'dev/atomic-dev/atomic-ads-publisher-service-dev/atomic-ads-publisher-service-faq',
                    ],
                  },
                ],
              },
              {
                type: 'category',
                label: '场景化组件',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-scenariofusion-development/atomic-scenariofusion-development',
                  'dev/atomic-dev/atomic-scenariofusion-development/scenario-fusion-atomic-introduction',
                  {
                    type: 'category',
                    label: '场景化Button',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/scenario-fusion-atomic-button/scenario-fusion-atomic-button',
                      'dev/atomic-dev/scenario-fusion-atomic-button/scenario-fusion-button-atomic-getservicecode',
                      'dev/atomic-dev/scenario-fusion-atomic-button/scenario-fusion-button-atomic-service-share',
                      'dev/atomic-dev/scenario-fusion-atomic-button/scenario-fusion-button-atomic-feedback',
                    ],
                  },
                ],
              },
              {
                type: 'category',
                label: '应用市场',
                collapsed: true,
                items: [
                  'dev/atomic-dev/atomic-appgallery-development/atomic-appgallery-development',
                  'dev/atomic-dev/atomic-appgallery-development/atomic-appgallery-introduction',
                  'dev/atomic-dev/atomic-appgallery-development/atomic-appgallery-update',
                ],
              },
            ],
          },
          {
            type: 'category',
            label: '应用和元服务可复用设计',
            collapsed: true,
            items: [
              'dev/atomic-dev/app-atomic-service-reusable/app-atomic-service-reusable',
              {
                type: 'category',
                label: '开发态可复用设计',
                collapsed: true,
                items: [
                  'dev/atomic-dev/reusable-develop-state/reusable-develop-state',
                  'dev/atomic-dev/reusable-develop-state/reusable-develop-state-design',
                  'dev/atomic-dev/reusable-develop-state/reusable-develop-state-develop',
                ],
              },
              {
                type: 'category',
                label: '运行态可复用设计',
                collapsed: true,
                items: [
                  'dev/atomic-dev/reusable-runtime-state/reusable-runtime-state',
                  'dev/atomic-dev/reusable-runtime-state/reusable-runtime-state-design',
                  'dev/atomic-dev/reusable-runtime-state/reusable-runtime-state-develop',
                ],
              },
            ],
          },
        ],
      },
      {
        type: 'category',
        label: '运行调试元服务',
        collapsed: true,
        items: [
          'dev/atomic-dev/atomic-running-debugging/atomic-running-debugging',
          'dev/atomic-dev/atomic-running-debugging/atomic-service-appanalyzer',
          'dev/atomic-dev/atomic-running-debugging/atomic-service-check',
        ],
      },
      {
        type: 'category',
        label: '元服务核准（备案）',
        collapsed: true,
        items: [
          'dev/atomic-dev/atomic-service-filing/atomic-service-filing',
          'dev/atomic-dev/atomic-service-filing/atomic-service-filing-preparation',
          {
            type: 'category',
            label: '在华为云核准（备案）系统备案',
            collapsed: true,
            items: [
              'dev/atomic-dev/atomic-service-cloud/atomic-service-cloud',
              'dev/atomic-dev/atomic-service-cloud/atomic-service-filing-first',
              'dev/atomic-dev/atomic-service-cloud/atomic-service-filing-internet-info',
              'dev/atomic-dev/atomic-service-cloud/atomic-service-filing-transfer',
              'dev/atomic-dev/atomic-service-cloud/atomic-service-filing-change',
              'dev/atomic-dev/atomic-service-cloud/atomic-service-filing-log-out',
              'dev/atomic-dev/atomic-service-cloud/atomic-service-filing-cancel',
            ],
          },
          'dev/atomic-dev/atomic-service-filing/atomic-service-filing-sms',
        ],
      },
      'dev/atomic-dev/atomic-service-debug-release',
      {
        type: 'category',
        label: '服务直达支持元服务',
        collapsed: true,
        items: [
          'dev/atomic-dev/instant-service/instant-service',
          'dev/atomic-dev/instant-service/instant-service-overview',
          'dev/atomic-dev/instant-service/instant-service-role-permissions',
          {
            type: 'category',
            label: '通过界面接入服务直达',
            collapsed: true,
            items: [
              'dev/atomic-dev/instant-service-gui/instant-service-gui',
              {
                type: 'category',
                label: '门店',
                collapsed: true,
                items: [
                  'dev/atomic-dev/instant-service-store/instant-service-store',
                  'dev/atomic-dev/instant-service-store/instant-service-store-batch-create',
                  'dev/atomic-dev/instant-service-store/instant-service-store-batch-update',
                  'dev/atomic-dev/instant-service-store/instant-service-store-cover-management',
                  'dev/atomic-dev/instant-service-store/instant-service-store-batch-export',
                  'dev/atomic-dev/instant-service-store/instant-service-store-batch-tasks',
                  'dev/atomic-dev/instant-service-store/instant-service-store-batch-delete',
                ],
              },
              {
                type: 'category',
                label: '子服务',
                collapsed: true,
                items: [
                  'dev/atomic-dev/instant-service-items/instant-service-items',
                  'dev/atomic-dev/instant-service-items/instant-service-items-create-pers',
                  'dev/atomic-dev/instant-service-items/preview-sub-service-card',
                  'dev/atomic-dev/instant-service-items/instant-service-items-update',
                  'dev/atomic-dev/instant-service-items/instant-service-items-pers-update',
                  'dev/atomic-dev/instant-service-items/instant-service-items-pers-delist',
                  'dev/atomic-dev/instant-service-items/instant-service-items-pers-add',
                  'dev/atomic-dev/instant-service-items/instant-service-items-batch-create',
                  'dev/atomic-dev/instant-service-items/instant-service-items-batch-update',
                ],
              },
              {
                type: 'category',
                label: '服务卡片（FormKit）',
                collapsed: true,
                items: [
                  'dev/atomic-dev/instant-service-formkit/instant-service-formkit',
                  'dev/atomic-dev/instant-service-formkit/instant-service-formkit-create',
                  'dev/atomic-dev/instant-service-formkit/instant-service-formkit-preview',
                  'dev/atomic-dev/instant-service-formkit/instant-service-formkit-update',
                  'dev/atomic-dev/instant-service-formkit/instant-service-formkit-remove',
                ],
              },
              {
                type: 'category',
                label: '商品',
                collapsed: true,
                items: [
                  'dev/atomic-dev/instant-service-offerings/instant-service-offerings',
                  'dev/atomic-dev/instant-service-offerings/instant-service-offerings-batch-create',
                  'dev/atomic-dev/instant-service-offerings/instant-service-offerings-batch-update',
                  'dev/atomic-dev/instant-service-offerings/instant-service-offerings-batch-export',
                  'dev/atomic-dev/instant-service-offerings/instant-service-offerings-batch-delist',
                  'dev/atomic-dev/instant-service-offerings/instant-service-offerings-batch-delete',
                ],
              },
            ],
          },
          {
            type: 'category',
            label: '通过API接入服务直达',
            collapsed: true,
            items: [
              'dev/atomic-dev/instant-service-apis/instant-service-apis',
              {
                type: 'category',
                label: '入门指引',
                collapsed: true,
                items: [
                  'dev/atomic-dev/instant-service-getting-started/instant-service-getting-started',
                  'dev/atomic-dev/instant-service-getting-started/instant-service-service-providers',
                  'dev/atomic-dev/instant-service-getting-started/instant-service-merchants',
                  {
                    type: 'category',
                    label: '配置接口访问凭证',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/instant-service-access-credentials/instant-service-access-credentials',
                      'dev/atomic-dev/instant-service-access-credentials/instant-service-provider-authentication',
                      'dev/atomic-dev/instant-service-access-credentials/instant-service-merchant-authentication',
                    ],
                  },
                ],
              },
              {
                type: 'category',
                label: '图片管理',
                collapsed: true,
                items: [
                  'dev/atomic-dev/instant-service-image-management/instant-service-image-management',
                  'dev/atomic-dev/instant-service-image-management/instant-service-image-upload',
                ],
              },
              {
                type: 'category',
                label: '门店管理',
                collapsed: true,
                items: [
                  'dev/atomic-dev/instant-service-store-management/instant-service-store-management',
                  'dev/atomic-dev/instant-service-store-management/instant-service-store-process',
                  'dev/atomic-dev/instant-service-store-management/instant-service-store-create',
                  'dev/atomic-dev/instant-service-store-management/instant-service-store-query',
                  'dev/atomic-dev/instant-service-store-management/instant-service-store-update',
                  'dev/atomic-dev/instant-service-store-management/instant-service-store-delete',
                  'dev/atomic-dev/instant-service-store-management/instant-service-store-list',
                ],
              },
              {
                type: 'category',
                label: '商品管理',
                collapsed: true,
                items: [
                  'dev/atomic-dev/instant-service-offerings-management/instant-service-offerings-management',
                  'dev/atomic-dev/instant-service-offerings-management/instant-service-offerings-process',
                  'dev/atomic-dev/instant-service-offerings-management/instant-service-offerings-create',
                  'dev/atomic-dev/instant-service-offerings-management/instant-service-offerings-query',
                  'dev/atomic-dev/instant-service-offerings-management/instant-service-offerings-update',
                  'dev/atomic-dev/instant-service-offerings-management/instant-service-offerings-direct-update',
                  'dev/atomic-dev/instant-service-offerings-management/instant-service-offerings-delist',
                  'dev/atomic-dev/instant-service-offerings-management/instant-service-offerings-terminate-review',
                  'dev/atomic-dev/instant-service-offerings-management/instant-service-offerings-delete',
                  'dev/atomic-dev/instant-service-offerings-management/instant-service-offerings-list',
                  'dev/atomic-dev/instant-service-offerings-management/instant-service-offerings-attributes',
                ],
              },
              'dev/atomic-dev/instant-service-apis/instant-service-error-code',
            ],
          },
          'dev/atomic-dev/instant-service/instant-service-warehouse-review',
          'dev/atomic-dev/instant-service/instant-service-inclusion',
          'dev/atomic-dev/instant-service/instant-service-card-spec',
          {
            type: 'category',
            label: '获取跳转链接',
            collapsed: true,
            items: [
              'dev/atomic-dev/instant-service-jump-link/instant-service-jump-link',
              'dev/atomic-dev/instant-service-jump-link/instant-service-jump-link-want',
            ],
          },
        ],
      },
      {
        type: 'category',
        label: '服务直达支持应用',
        collapsed: true,
        items: [
          'dev/atomic-dev/instant-service-app/instant-service-app',
          {
            type: 'category',
            label: '通过界面接入服务直达',
            collapsed: true,
            items: [
              'dev/atomic-dev/instant-service-app-gui/instant-service-app-gui',
              'dev/atomic-dev/instant-service-app-gui/instant-service-app-gui-overview',
              'dev/atomic-dev/instant-service-app-gui/instant-service-app-role-permissions',
              {
                type: 'category',
                label: '门店',
                collapsed: true,
                items: [
                  'dev/atomic-dev/instant-service-app-store/instant-service-app-store',
                  'dev/atomic-dev/instant-service-app-store/instant-service-app-store-batch-create',
                  'dev/atomic-dev/instant-service-app-store/instant-service-app-store-batch-export',
                  'dev/atomic-dev/instant-service-app-store/instant-service-app-store-batch-update',
                  'dev/atomic-dev/instant-service-app-store/instant-service-app-store-batch-tasks',
                  'dev/atomic-dev/instant-service-app-store/instant-service-app-store-batch-delete',
                ],
              },
              {
                type: 'category',
                label: '子服务',
                collapsed: true,
                items: [
                  'dev/atomic-dev/instant-service-app-items/instant-service-app-items',
                  'dev/atomic-dev/instant-service-app-items/instant-service-app-items-create-pers',
                  'dev/atomic-dev/instant-service-app-items/instant-service-app-items-preview',
                  'dev/atomic-dev/instant-service-app-items/instant-service-app-items-update',
                  'dev/atomic-dev/instant-service-app-items/instant-service-app-items-pers-update',
                  'dev/atomic-dev/instant-service-app-items/instant-service-app-items-pers-delist',
                  'dev/atomic-dev/instant-service-app-items/instant-service-app-items-pers-add',
                ],
              },
              {
                type: 'category',
                label: '商品',
                collapsed: true,
                items: [
                  'dev/atomic-dev/instant-service-app-offerings/instant-service-app-offerings',
                  'dev/atomic-dev/instant-service-app-offerings/instant-service-app-offerings-batch-create',
                  'dev/atomic-dev/instant-service-app-offerings/instant-service-app-offerings-batch-update',
                  'dev/atomic-dev/instant-service-app-offerings/instant-service-app-offerings-batch-export',
                  'dev/atomic-dev/instant-service-app-offerings/instant-service-app-offerings-batch-delist',
                  'dev/atomic-dev/instant-service-app-offerings/instant-service-app-offerings-batch-delete',
                ],
              },
            ],
          },
        ],
      },
      {
        type: 'category',
        label: '元服务规范',
        collapsed: true,
        items: [
          'dev/atomic-dev/atomic-service-specifications/atomic-service-specifications',
          'dev/atomic-dev/atomic-service-specifications/atomic-service-ecosystem-operations',
          'dev/atomic-dev/atomic-service-specifications/atomic-service-naming-conversion',
        ],
      },
    ],
  },
  {
    type: 'category',
    label: 'ASCF 跨平台框架',
    collapsed: true,
    items: [
      'dev/atomic-dev/ascf/ascf-overview',
      'dev/atomic-dev/ascf/ascf-plugin',
      {
        type: 'category',
        label: '开发流程',
        collapsed: true,
        items: [
          'dev/atomic-dev/ascf/ascf-development-process/ascf-development-process',
          {
            type: 'category',
            label: '在DevEco Studio中开发',
            collapsed: true,
            items: [
              'dev/atomic-dev/ascf/use-ide/use-ide',
              'dev/atomic-dev/ascf/use-ide/create-ascf-project',
              'dev/atomic-dev/ascf/use-ide/convert-atomic-service-resources',
              'dev/atomic-dev/ascf/use-ide/compile-atomic-service',
              'dev/atomic-dev/ascf/use-ide/compile-ascf-paradigm',
              'dev/atomic-dev/ascf/use-ide/create-atomic-service',
            ],
          },
          'dev/atomic-dev/ascf/ascf-development-process/ascf-cross-atomicservice',
          'dev/atomic-dev/ascf/ascf-development-process/run-ascf-cli',
          'dev/atomic-dev/ascf/ascf-development-process/ascf-assistant',
          'dev/atomic-dev/ascf/ascf-development-process/ascf-bitfun',
          'dev/atomic-dev/ascf/ascf-development-process/code-editing',
          'dev/atomic-dev/ascf/ascf-development-process/configuring-signature',
          'dev/atomic-dev/ascf/ascf-development-process/debug-ascf-code',
          'dev/atomic-dev/ascf/ascf-development-process/release-atomic-service',
        ],
      },
      {
        type: 'category',
        label: '开发指南',
        collapsed: true,
        items: [
          'dev/atomic-dev/ascf/ascf-development-guide/ascf-development-guide',
          {
            type: 'category',
            label: '基础能力',
            collapsed: true,
            items: [
              'dev/atomic-dev/ascf/develop-basic-capabilities/develop-basic-capabilities',
              'dev/atomic-dev/ascf/develop-basic-capabilities/develop-network-access',
              {
                type: 'category',
                label: '分包加载',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/develop-subpackage-loading/develop-subpackage-loading',
                  'dev/atomic-dev/ascf/develop-subpackage-loading/develop-subpackages',
                  'dev/atomic-dev/ascf/develop-subpackage-loading/develop-preloading',
                  'dev/atomic-dev/ascf/develop-subpackage-loading/asynchronous-subcontracting',
                  'dev/atomic-dev/ascf/develop-subpackage-loading/develop-ide-runtime-configuration',
                ],
              },
              'dev/atomic-dev/ascf/develop-basic-capabilities/develop-canvas',
              'dev/atomic-dev/ascf/develop-basic-capabilities/develop-data-storage',
              'dev/atomic-dev/ascf/develop-basic-capabilities/develop-media-access',
              'dev/atomic-dev/ascf/develop-basic-capabilities/develop-page-node-retrieval',
              {
                type: 'category',
                label: '安全',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/develop-security/develop-security',
                  'dev/atomic-dev/ascf/develop-security/content-moderation-service',
                ],
              },
              'dev/atomic-dev/ascf/develop-basic-capabilities/develop-authorization',
              'dev/atomic-dev/ascf/develop-basic-capabilities/develop-immersive-pages',
              'dev/atomic-dev/ascf/develop-basic-capabilities/develop-custom-tabbar',
              'dev/atomic-dev/ascf/develop-basic-capabilities/on-demand-render-time-injection',
              'dev/atomic-dev/ascf/develop-basic-capabilities/develop-blocked-update',
              'dev/atomic-dev/ascf/develop-basic-capabilities/develop-data-preloading',
              'dev/atomic-dev/ascf/develop-basic-capabilities/develop-open-atomicservice-with-parameters',
              'dev/atomic-dev/ascf/develop-basic-capabilities/develop-want-parameter-parsing',
            ],
          },
          {
            type: 'category',
            label: '开放能力',
            collapsed: true,
            items: [
              'dev/atomic-dev/ascf/develop-open-capabilities/develop-open-capabilities',
              'dev/atomic-dev/ascf/develop-open-capabilities/develop-huawei-id-retrieval',
              'dev/atomic-dev/ascf/develop-open-capabilities/develop-location-retrieval',
              'dev/atomic-dev/ascf/develop-open-capabilities/develop-push-info',
              'dev/atomic-dev/ascf/develop-open-capabilities/develop-payment-access',
              'dev/atomic-dev/ascf/develop-open-capabilities/develop-web-view',
              'dev/atomic-dev/ascf/develop-open-capabilities/develop-navigate-other-atomicservices',
              'dev/atomic-dev/ascf/develop-open-capabilities/ascf-applinking',
              'dev/atomic-dev/ascf/develop-open-capabilities/develop-privacy-hosting',
              'dev/atomic-dev/ascf/develop-open-capabilities/develop-open-embedded-atomicservice',
            ],
          },
          {
            type: 'category',
            label: '开发服务卡片',
            collapsed: true,
            items: [
              'dev/atomic-dev/ascf/develop-widget/develop-widget',
              'dev/atomic-dev/ascf/develop-widget/atomic-service-form-share-storage-data',
            ],
          },
          'dev/atomic-dev/ascf/ascf-development-guide/ascf-cross-guide',
        ],
      },
      {
        type: 'category',
        label: 'API参考',
        collapsed: true,
        items: [
          'dev/atomic-dev/ascf/ascf-references/ascf-references',
          {
            type: 'category',
            label: '框架',
            collapsed: true,
            items: [
              'dev/atomic-dev/ascf/framework/framework',
              'dev/atomic-dev/ascf/framework/file-structure',
              {
                type: 'category',
                label: '配置',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/config/config',
                  'dev/atomic-dev/ascf/config/appjson-global-config',
                  'dev/atomic-dev/ascf/config/page-json-config',
                  'dev/atomic-dev/ascf/config/project-json-config',
                ],
              },
              {
                type: 'category',
                label: '视图层',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/view-layer/view-layer',
                  'dev/atomic-dev/ascf/view-layer/view-layer-hxml',
                  'dev/atomic-dev/ascf/view-layer/view-layer-css',
                ],
              },
              {
                type: 'category',
                label: '逻辑层',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/logical-layer/logical-layer',
                  'dev/atomic-dev/ascf/logical-layer/logical-layer-js',
                  'dev/atomic-dev/ascf/logical-layer/logical-layer-app',
                  'dev/atomic-dev/ascf/logical-layer/logical-layer-page',
                  'dev/atomic-dev/ascf/logical-layer/logical-layer-route-lifecycle',
                  {
                    type: 'category',
                    label: '事件系统',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/ascf/logical-layer-events/logical-layer-events',
                      'dev/atomic-dev/ascf/logical-layer-events/logical-layer-event-usage',
                      'dev/atomic-dev/ascf/logical-layer-events/logical-layer-event-responding-hjs',
                      'dev/atomic-dev/ascf/logical-layer-events/logical-layer-event-category',
                      'dev/atomic-dev/ascf/logical-layer-events/logical-layer-event-binding-bubbling',
                      'dev/atomic-dev/ascf/logical-layer-events/logical-layer-event-capture',
                      'dev/atomic-dev/ascf/logical-layer-events/logical-layer-event-object',
                      'dev/atomic-dev/ascf/logical-layer-events/logical-layer-event-bidirectional-binding',
                    ],
                  },
                ],
              },
              {
                type: 'category',
                label: '自定义组件',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/custom-components/custom-components',
                  {
                    type: 'category',
                    label: '介绍',
                    collapsed: true,
                    items: [
                      'dev/atomic-dev/ascf/custom-components-overview/custom-components-overview',
                      'dev/atomic-dev/ascf/custom-components-overview/custom-components-template',
                      'dev/atomic-dev/ascf/custom-components-overview/custom-components-hxml-slot',
                      'dev/atomic-dev/ascf/custom-components-overview/custom-components-style-isolation',
                      'dev/atomic-dev/ascf/custom-components-overview/custom-components-component',
                      'dev/atomic-dev/ascf/custom-components-overview/custom-components-lifecycle',
                      'dev/atomic-dev/ascf/custom-components-overview/custom-components-creation',
                      'dev/atomic-dev/ascf/custom-components-overview/custom-components-usage',
                    ],
                  },
                  'dev/atomic-dev/ascf/custom-components/custom-components-communication',
                  'dev/atomic-dev/ascf/custom-components/custom-components-observers',
                  'dev/atomic-dev/ascf/custom-components/component-placeholder',
                ],
              },
              {
                type: 'category',
                label: 'hjs',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/hjs/hjs',
                  'dev/atomic-dev/ascf/hjs/hjs-responding-event',
                ],
              },
              'dev/atomic-dev/ascf/framework/ascf-referer',
              'dev/atomic-dev/ascf/framework/ascf-nativebridge',
            ],
          },
          {
            type: 'category',
            label: '组件',
            collapsed: true,
            items: [
              'dev/atomic-dev/ascf/components/components',
              {
                type: 'category',
                label: '视图容器',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/components-view-container/components-view-container',
                  'dev/atomic-dev/ascf/components-view-container/components-movable-area',
                  'dev/atomic-dev/ascf/components-view-container/components-movable-view',
                  'dev/atomic-dev/ascf/components-view-container/components-scroll-view',
                  'dev/atomic-dev/ascf/components-view-container/components-swiper',
                  'dev/atomic-dev/ascf/components-view-container/components-swiper-item',
                  'dev/atomic-dev/ascf/components-view-container/components-view',
                  'dev/atomic-dev/ascf/components-view-container/components-cover-view',
                  'dev/atomic-dev/ascf/components-view-container/components-cover-image',
                ],
              },
              {
                type: 'category',
                label: '基础内容',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/components-basic-components/components-basic-components',
                  'dev/atomic-dev/ascf/components-basic-components/components-icon',
                  'dev/atomic-dev/ascf/components-basic-components/components-progress',
                  'dev/atomic-dev/ascf/components-basic-components/components-rich-text',
                  'dev/atomic-dev/ascf/components-basic-components/components-text',
                ],
              },
              {
                type: 'category',
                label: '表单组件',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/components-form-components/components-form-components',
                  'dev/atomic-dev/ascf/components-form-components/components-button',
                  'dev/atomic-dev/ascf/components-form-components/components-checkbox',
                  'dev/atomic-dev/ascf/components-form-components/components-checkbox-group',
                  'dev/atomic-dev/ascf/components-form-components/components-form',
                  'dev/atomic-dev/ascf/components-form-components/components-input',
                  'dev/atomic-dev/ascf/components-form-components/components-label',
                  'dev/atomic-dev/ascf/components-form-components/components-picker',
                  'dev/atomic-dev/ascf/components-form-components/components-picker-view',
                  'dev/atomic-dev/ascf/components-form-components/components-picker-view-column',
                  'dev/atomic-dev/ascf/components-form-components/components-radio',
                  'dev/atomic-dev/ascf/components-form-components/components-radio-group',
                  'dev/atomic-dev/ascf/components-form-components/components-slider',
                  'dev/atomic-dev/ascf/components-form-components/components-switch',
                  'dev/atomic-dev/ascf/components-form-components/components-textarea',
                  'dev/atomic-dev/ascf/components-form-components/components-editor',
                ],
              },
              {
                type: 'category',
                label: '导航',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/components-navigation-components/components-navigation-components',
                  'dev/atomic-dev/ascf/components-navigation-components/components-navigator',
                ],
              },
              {
                type: 'category',
                label: '媒体组件',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/components-media-components/components-media-components',
                  'dev/atomic-dev/ascf/components-media-components/components-image',
                  'dev/atomic-dev/ascf/components-media-components/components-video',
                  'dev/atomic-dev/ascf/components-media-components/components-camera',
                  'dev/atomic-dev/ascf/components-media-components/components-audio',
                ],
              },
              {
                type: 'category',
                label: '地图',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/components-map-components/components-map-components',
                  'dev/atomic-dev/ascf/components-map-components/components-map',
                ],
              },
              {
                type: 'category',
                label: '画布',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/components-canvas-components/components-canvas-components',
                  'dev/atomic-dev/ascf/components-canvas-components/components-canvas',
                ],
              },
              'dev/atomic-dev/ascf/components/components-web-view',
              {
                type: 'category',
                label: '开放能力',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/components-open-capabilities/components-open-capabilities',
                  'dev/atomic-dev/ascf/components-open-capabilities/components-open-embedded-atomicservice',
                ],
              },
            ],
          },
          {
            type: 'category',
            label: 'API',
            collapsed: true,
            items: [
              'dev/atomic-dev/ascf/apis/apis',
              {
                type: 'category',
                label: '基础',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/apis-basis/apis-basis',
                  'dev/atomic-dev/ascf/apis-basis/apis-caniuse',
                  'dev/atomic-dev/ascf/apis-basis/apis-system-info',
                  'dev/atomic-dev/ascf/apis-basis/apis-lifecycle',
                  'dev/atomic-dev/ascf/apis-basis/apis-app-event',
                  'dev/atomic-dev/ascf/apis-basis/apis-debug',
                  'dev/atomic-dev/ascf/apis-basis/apis-timer',
                  'dev/atomic-dev/ascf/apis-basis/apis-service-info',
                  'dev/atomic-dev/ascf/apis-basis/apis-format-conversion',
                  'dev/atomic-dev/ascf/apis-basis/apis-updatemanager',
                ],
              },
              'dev/atomic-dev/ascf/apis/apis-router',
              'dev/atomic-dev/ascf/apis/apis-navigate',
              'dev/atomic-dev/ascf/apis/apis-nativebridge',
              {
                type: 'category',
                label: '界面',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/apis-page/apis-page',
                  'dev/atomic-dev/ascf/apis-page/apis-interaction',
                  'dev/atomic-dev/ascf/apis-page/apis-navigation',
                  'dev/atomic-dev/ascf/apis-page/apis-tab-bar',
                  'dev/atomic-dev/ascf/apis-page/apis-font',
                  'dev/atomic-dev/ascf/apis-page/apis-pull-down-refresh',
                  'dev/atomic-dev/ascf/apis-page/apis-scroll',
                  'dev/atomic-dev/ascf/apis-page/apis-animation',
                  'dev/atomic-dev/ascf/apis-page/apis-menu',
                  'dev/atomic-dev/ascf/apis-page/apis-custom-components',
                  'dev/atomic-dev/ascf/apis-page/apis-window',
                ],
              },
              {
                type: 'category',
                label: '网络',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/apis-network/apis-network',
                  'dev/atomic-dev/ascf/apis-network/apis-request',
                  'dev/atomic-dev/ascf/apis-network/apis-download',
                  'dev/atomic-dev/ascf/apis-network/apis-upload',
                  'dev/atomic-dev/ascf/apis-network/apis-websocket',
                ],
              },
              'dev/atomic-dev/ascf/apis/apis-data-storage',
              {
                type: 'category',
                label: '媒体',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/apis-media/apis-media',
                  'dev/atomic-dev/ascf/apis-media/apis-map',
                  'dev/atomic-dev/ascf/apis-media/apis-image',
                  'dev/atomic-dev/ascf/apis-media/apis-video',
                  'dev/atomic-dev/ascf/apis-media/apis-camera',
                  'dev/atomic-dev/ascf/apis-media/apis-audio',
                  'dev/atomic-dev/ascf/apis-media/apis-background-audio',
                  'dev/atomic-dev/ascf/apis-media/apis-record',
                  'dev/atomic-dev/ascf/apis-media/apis-rich-text',
                ],
              },
              'dev/atomic-dev/ascf/apis/apis-file',
              'dev/atomic-dev/ascf/apis/apis-location',
              'dev/atomic-dev/ascf/apis/apis-canvas',
              {
                type: 'category',
                label: '开放接口',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/apis-open-apis/apis-open-apis',
                  'dev/atomic-dev/ascf/apis-open-apis/apis-account',
                  'dev/atomic-dev/ascf/apis-open-apis/apis-authorization',
                  'dev/atomic-dev/ascf/apis-open-apis/apis-setting',
                  'dev/atomic-dev/ascf/apis-open-apis/apis-payment',
                  'dev/atomic-dev/ascf/apis-open-apis/apis-privacy',
                  'dev/atomic-dev/ascf/apis-open-apis/apis-message-subscription',
                  'dev/atomic-dev/ascf/apis-open-apis/apis-shipping-address',
                  'dev/atomic-dev/ascf/apis-open-apis/apis-invoice',
                  'dev/atomic-dev/ascf/apis-open-apis/apis-iap',
                  'dev/atomic-dev/ascf/apis-open-apis/apis-realname',
                  'dev/atomic-dev/ascf/apis-open-apis/apis-share',
                  'dev/atomic-dev/ascf/apis-open-apis/apis-user-info',
                ],
              },
              {
                type: 'category',
                label: '设备',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/apis-device/apis-device',
                  'dev/atomic-dev/ascf/apis-device/apis-network-type',
                  'dev/atomic-dev/ascf/apis-device/apis-telephony',
                  'dev/atomic-dev/ascf/apis-device/apis-device-orientation',
                  'dev/atomic-dev/ascf/apis-device/apis-scan',
                  'dev/atomic-dev/ascf/apis-device/apis-vibrator',
                  'dev/atomic-dev/ascf/apis-device/apis-battery-info',
                  'dev/atomic-dev/ascf/apis-device/apis-calendar',
                  'dev/atomic-dev/ascf/apis-device/apis-bluetooth',
                  'dev/atomic-dev/ascf/apis-device/apis-ble',
                  'dev/atomic-dev/ascf/apis-device/apis-contact',
                  'dev/atomic-dev/ascf/apis-device/apis-wifi',
                  'dev/atomic-dev/ascf/apis-device/apis-screen',
                  'dev/atomic-dev/ascf/apis-device/apis-accelerometer',
                  'dev/atomic-dev/ascf/apis-device/apis-compass',
                  'dev/atomic-dev/ascf/apis-device/apis-gyroscope',
                  'dev/atomic-dev/ascf/apis-device/apis-keyboard',
                  'dev/atomic-dev/ascf/apis-device/apis-clipboard',
                  'dev/atomic-dev/ascf/apis-device/apis-crypto',
                  'dev/atomic-dev/ascf/apis-device/apis-memory',
                ],
              },
              'dev/atomic-dev/ascf/apis/apis-third-party-platform',
              'dev/atomic-dev/ascf/apis/apis-hxml',
              'dev/atomic-dev/ascf/apis/apis-push-service',
              {
                type: 'category',
                label: 'AI',
                collapsed: true,
                items: [
                  'dev/atomic-dev/ascf/apis-ai/apis-ai',
                  'dev/atomic-dev/ascf/apis-ai/apis-ai-face-liveness-detection',
                ],
              },
            ],
          },
        ],
      },
      {
        type: 'category',
        label: '常见问题',
        collapsed: true,
        items: [
          'dev/atomic-dev/ascf/faqs/faqs',
          {
            type: 'category',
            label: 'ASCF Plugin',
            collapsed: true,
            items: [
              'dev/atomic-dev/ascf/faqs-ascf-plugin/faqs-ascf-plugin',
              'dev/atomic-dev/ascf/faqs-ascf-plugin/faqs-plugin-template-not-found',
              'dev/atomic-dev/ascf/faqs-ascf-plugin/faqs-plugin-debugging-error',
              'dev/atomic-dev/ascf/faqs-ascf-plugin/faqs-plugin-not-upgraded',
              'dev/atomic-dev/ascf/faqs-ascf-plugin/faqs-plugin-unsupported-syntax',
              'dev/atomic-dev/ascf/faqs-ascf-plugin/faqs-plugin-hot-reload',
            ],
          },
          {
            type: 'category',
            label: 'ASCF Toolkit',
            collapsed: true,
            items: [
              'dev/atomic-dev/ascf/faqs-ascf-toolkit/faqs-ascf-toolkit',
              'dev/atomic-dev/ascf/faqs-ascf-toolkit/faqs-toolkit-output-path-error',
              'dev/atomic-dev/ascf/faqs-ascf-toolkit/faqs-toolkit-path-received-undefined',
              'dev/atomic-dev/ascf/faqs-ascf-toolkit/faqs-toolkit-build-profile-not-found',
              'dev/atomic-dev/ascf/faqs-ascf-toolkit/faqs-toolkit-contains-error',
              'dev/atomic-dev/ascf/faqs-ascf-toolkit/faqs-toolkit-properties-undefined',
              'dev/atomic-dev/ascf/faqs-ascf-toolkit/faqs-toolkit-failed-execute-createelement',
              'dev/atomic-dev/ascf/faqs-ascf-toolkit/faqs-hsp-dependency-check-error',
              'dev/atomic-dev/ascf/faqs-ascf-toolkit/faqs-referenced-asynchronously-displayed',
              'dev/atomic-dev/ascf/faqs-ascf-toolkit/faqs-toolkit-error-unknown-option-serve',
              'dev/atomic-dev/ascf/faqs-ascf-toolkit/faqs-toolkit-devtool-manual-installation',
              'dev/atomic-dev/ascf/faqs-ascf-toolkit/faqs-appjson-pages-change',
              'dev/atomic-dev/ascf/faqs-ascf-toolkit/faqs-uniapp-sourcemap-generation',
              'dev/atomic-dev/ascf/faqs-ascf-toolkit/faqs-quickapp-loader-manual-installation',
              'dev/atomic-dev/ascf/faqs-ascf-toolkit/faqs-toolkit-install-hsp-faild',
              'dev/atomic-dev/ascf/faqs-ascf-toolkit/faqs-toolkit-require-invalid',
            ],
          },
          {
            type: 'category',
            label: 'ASCF运行时',
            collapsed: true,
            items: [
              'dev/atomic-dev/ascf/faqs-ascf-runtime/faqs-ascf-runtime',
              'dev/atomic-dev/ascf/faqs-ascf-runtime/faqs-runtime-login-error',
              'dev/atomic-dev/ascf/faqs-ascf-runtime/faqs-runtime-properties-not-defined',
              'dev/atomic-dev/ascf/faqs-ascf-runtime/faqs-runtime-hot-reload',
              'dev/atomic-dev/ascf/faqs-ascf-runtime/faqs-runtime-emulator',
              'dev/atomic-dev/ascf/faqs-ascf-runtime/faqs-runtime-library-version',
              'dev/atomic-dev/ascf/faqs-ascf-runtime/faqs-runtime-map-duplicate-marker-id',
            ],
          },
          {
            type: 'category',
            label: '其他问题',
            collapsed: true,
            items: [
              'dev/atomic-dev/ascf/faqs-others/faqs-others',
              'dev/atomic-dev/ascf/faqs-others/faqs-others-agc-upload-errorcode9',
              'dev/atomic-dev/ascf/faqs-others/faqs-others-running-abnormally',
              'dev/atomic-dev/ascf/faqs-others/faqs-others-hot-reload',
              'dev/atomic-dev/ascf/faqs-others/faqs-others-cloud-debugging',
              'dev/atomic-dev/ascf/faqs-others/faqs-uniapp-ascf',
              'dev/atomic-dev/ascf/faqs-others/faqs-button-width-problem',
            ],
          },
          'dev/atomic-dev/ascf/faqs/faqs-diff-ascf-applets',
        ],
      },
      {
        type: 'category',
        label: '版本变更说明',
        collapsed: true,
        items: [
          'dev/atomic-dev/ascf/ascf-release-note/ascf-release-note',
          'dev/atomic-dev/ascf/ascf-release-note/release-note-ascf-runtime',
          'dev/atomic-dev/ascf/ascf-release-note/release-note-ascf-plugin',
          'dev/atomic-dev/ascf/ascf-release-note/release-note-ascf-toolkit',
          'dev/atomic-dev/ascf/ascf-release-note/release-note-ascf-vscode',
          'dev/atomic-dev/ascf/ascf-release-note/release-note-ascf-bitfun',
        ],
      },
    ],
  },
];

module.exports = { atomicSidebar };
