/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  guideSidebar: [
    {
      type: 'html',
      value: '<div style="text-indent: 4px;">入门</div>', 
    },
    'guides/startup/preparation',
    'guides/startup/quick-start',
    'guides/startup/basic',
    'guides/startup/system-capability',
    'guides/startup/glossary',
    
    {
      type: 'html',
      value: '<div style="text-indent: 4px;"><hr>鸿蒙特征</div>', 
    },

    {
      type: 'category',
      label: '一次开发多端部署',
      link: {
        type: 'doc',
        id: 'guides/hmos/one-piece',
      },
      items: [
        'guides/hmos/one-piece/basic-concepts',
        'guides/hmos/one-piece/ui',
        'guides/hmos/one-piece/project',
        'guides/hmos/one-piece/page-development',
        'guides/hmos/one-piece/function-development',
        {
          type: 'category',
          label: '多设备应用开发',
          link: {
            type: 'doc',
            id: 'guides/hmos/one-piece/multi-device',
          },
          items: [
            'guides/hmos/one-piece/multi-device/foldable',
            'guides/hmos/one-piece/multi-device/wearable',
            'guides/hmos/one-piece/multi-device/tv',
            'guides/hmos/one-piece/multi-device/car',
            'guides/hmos/one-piece/multi-device/hicar',
          ],
        },
      ],
    },
    'guides/hmos/hopping',
    'guides/hmos/skelter',

    {
      type: 'html',
      value: '<div style="text-indent: 4px;"><hr>应用架构</div>', 
    },

    'guides/architecture/overview',
    'guides/architecture/layered',
    'guides/architecture/modular',
    'guides/architecture/navigation',
    'guides/architecture/reuse',

    {
      type: 'html',
      value: '<div style="text-indent: 4px;"><hr>开发</div>', 
    },

    {
      type: 'category',
      label: '基础框架能力',
      link: {
        type: 'doc',
        id: 'guides/dev/framework',
      },
      items: [
        {
          type: 'category',
          label: 'Ability Kit（程序框架服务）',
          link: {
            type: 'doc',
            id: 'guides/dev/framework/ability-kit',
          },
          items: [
            'guides/dev/framework/ability-kit/overview',
          ],
        },
      ],
    },

    'guides/dev/system',
    'guides/dev/media',
    'guides/dev/graphics',
    'guides/dev/services',
    'guides/dev/ai',

    {
      type: 'html',
      value: '<div style="text-indent: 4px;"><hr>测试</div>', 
    },

    'guides/test/overview',
    'guides/test/ut',
    'guides/test/test-service',

    {
      type: 'html',
      value: '<div style="text-indent: 4px;"><hr>最佳实践</div>', 
    },

    'guides/practices/performance',
    'guides/practices/security',

  ],
  atomicSidebar: [
    {
      type: 'html',
      value: '<div style="text-indent: 4px;">从这里开始</div>', 
    },
    'atomic/startup/overview',
    'atomic/startup/basic',
    'atomic/startup/glossary',
    {
      type: 'html',
      value: '<div style="text-indent: 4px;"><hr>新开发元服务</div>', 
    },
    'atomic/develop/development-journey',
    'atomic/develop/preparation',
    'atomic/develop/first-service',
    {
      type: 'category',
      label: '开放能力',
      link: {
        type: 'doc',
        id: 'atomic/develop/capability',
      },
      items: [
        'atomic/develop/capability/test',
        
      ],
    },

    {
      type: 'html',
      value: '<div style="text-indent: 4px;"><hr>迁移至元服务</div>', 
    },
    'atomic/migration/ascf',
    'atomic/migration/new-project',
    'atomic/migration/min-program',
    'atomic/migration/others',
    'atomic/migration/build',
    'atomic/migration/debug',
    {
      type: 'category',
      label: '开放能力',
      link: {
        type: 'doc',
        id: 'atomic/migration/capability',
      },
      items: [
        'atomic/migration/capability/network',
        'atomic/migration/capability/bundle',
        'atomic/migration/capability/canvas',
      ],
    },
    'atomic/migration/command-line-tools',
    {
      type: 'category',
      label: 'API参考',
      link: {
        type: 'doc',
        id: 'atomic/migration/api-ref',
      },
      items: [
        'atomic/migration/api-ref/framework',
        'atomic/migration/api-ref/component',
        'atomic/migration/api-ref/api',
      ],
    },


    {
      type: 'html',
      value: '<div style="text-indent: 4px;"><hr>发布元服务</div>', 
    },
    'atomic/release/check',
    'atomic/release/pack',
    'atomic/release/filings',
    'atomic/release/publish',
  ],

  arktsSidebar: [
    'arkts/intro',
    {
      type: 'category',
      label: '语法',
      link: {
        type: 'doc',
        id: 'arkts/syntax/index',
      },
      items: [
        'arkts/syntax/basics',
        'arkts/syntax/function',
        'arkts/syntax/class',
        'arkts/syntax/interface',
        'arkts/syntax/generic-type-and-function',
        'arkts/syntax/null-safety',
        'arkts/syntax/module',
        'arkts/syntax/keyword',
      ],
    },
    {
      type: 'category',
      label: 'ArkUI支持',
      link: {
        type: 'doc',
        id: 'arkts/arkui/index',
      },
      items: [
        {
          type: 'category',
          label: 'UI语法',
          link: {
            type: 'doc',
            id: 'arkts/arkui/ui-syntax/index',
          },
          items: [
            'arkts/arkui/ui-syntax/test',
          ],
        },
        {
          type: 'category',
          label: '状态管理V1',
          link: {
            type: 'doc',
            id: 'arkts/arkui/state-management/index',
          },
          items: [
            'arkts/arkui/state-management/test',
          ],
        },
        {
          type: 'category',
          label: '状态管理V2',
          link: {
            type: 'doc',
            id: 'arkts/arkui/state-management-v2/index',
          },
          items: [
            'arkts/arkui/state-management-v2/test',
          ],
        },
        {
          type: 'category',
          label: '渲染控制',
          link: {
            type: 'doc',
            id: 'arkts/arkui/rendering-control/index',
          },
          items: [
            'arkts/arkui/rendering-control/if-else',
            'arkts/arkui/rendering-control/foreach',
            'arkts/arkui/rendering-control/lazy-foreach',
            'arkts/arkui/rendering-control/content-slot',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '类库',
      link: {
        type: 'doc',
        id: 'arkts/library/index',
      },
      items: [
        'arkts/library/test',
      ],
    },
    {
      type: 'category',
      label: '并发',
      link: {
        type: 'doc',
        id: 'arkts/concurrency/index',
      },
      items: [
        'arkts/concurrency/test',
      ],
    },
    {
      type: 'category',
      label: '模块化',
      link: {
        type: 'doc',
        id: 'arkts/module/index',
      },
      items: [
        'arkts/module/test',
      ],
    },
    {
      type: 'category',
      label: '工具链',
      link: {
        type: 'doc',
        id: 'arkts/toolchain/index',
      },
      items: [
        'arkts/toolchain/test',
      ],
    },
    {
      type: 'category',
      label: '跨语言交互',
      link: {
        type: 'doc',
        id: 'arkts/cross-language/index',
      },
      items: [
        'arkts/cross-language/test',
      ],
    },
    {
      type: 'category',
      label: '编程规范',
      link: {
        type: 'doc',
        id: 'arkts/specification/index',
      },
      items: [
        'arkts/specification/test',
      ],
    },
    {
      type: 'category',
      label: '从TypeScript迁移',
      link: {
        type: 'doc',
        id: 'arkts/typescript/index',
      },
      items: [
        'arkts/typescript/test',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'doc',
        id: 'arkts/api/index',
      },
      items: [
        'arkts/api/api-list',
        'arkts/api/errorcode',
      ],
    },
  ],
  designSidebar: [
    'design/overview',
    {
      type: 'category',
      label: '通用设计基础',
      link: { type: 'doc', id: 'design/general-design-basics/index' },
      items: [        'design/general-design-basics/design-concepts',
        {
          type: 'category',
          label: '视觉风格',
          link: { type: 'doc', id: 'design/general-design-basics/visual-design/index' },
          items: [          'design/general-design-basics/visual-design/color',
          'design/general-design-basics/visual-design/font',
          'design/general-design-basics/visual-design/app-icon',
          'design/general-design-basics/visual-design/harmonyos-symbol'],
        },
        {
          type: 'category',
          label: '布局',
          link: { type: 'doc', id: 'design/general-design-basics/layout/index' },
          items: [          'design/general-design-basics/layout/layout-basics',
          'design/general-design-basics/layout/responsive-structure',
          'design/general-design-basics/layout/responsive-method'],
        },
        {
          type: 'category',
          label: '动效',
          link: { type: 'doc', id: 'design/general-design-basics/animation/index' },
          items: [          'design/general-design-basics/animation/overview',
          'design/general-design-basics/animation/principles',
          'design/general-design-basics/animation/attributes',
          'design/general-design-basics/animation/transition',
          'design/general-design-basics/animation/gesture'],
        },
        'design/general-design-basics/ui-language',
        'design/general-design-basics/globalization',
        'design/general-design-basics/privacy'],
    },
    {
      type: 'category',
      label: '控件',
      link: { type: 'doc', id: 'design/components/index' },
      items: [        'design/components/overview',
        {
          type: 'category',
          label: '导航类',
          link: { type: 'doc', id: 'design/components/navigation/index' },
          items: [          'design/components/navigation/bottom-tab',
          'design/components/navigation/chips-group',
          'design/components/navigation/title-bar',
          'design/components/navigation/swiper'],
        },
        {
          type: 'category',
          label: '展示类',
          link: { type: 'doc', id: 'design/components/view-components/index' },
          items: [          'design/components/view-components/text',
          'design/components/view-components/divider',
          'design/components/view-components/subheader',
          'design/components/view-components/progress',
          'design/components/view-components/alphabet-indexer',
          'design/components/view-components/scrollbar',
          'design/components/view-components/badge',
          'design/components/view-components/toast',
          'design/components/view-components/snackbar',
          'design/components/view-components/popup',
          'design/components/view-components/data-panel',
          'design/components/view-components/qrcode',
          'design/components/view-components/textclock',
          'design/components/view-components/image',
          'design/components/view-components/blank'],
        },
        {
          type: 'category',
          label: '操作类',
          link: { type: 'doc', id: 'design/components/control-components/index' },
          items: [          'design/components/control-components/button',
          'design/components/control-components/select',
          'design/components/control-components/toggle-button',
          'design/components/control-components/chips',
          'design/components/control-components/toolbar',
          'design/components/control-components/action-bar',
          'design/components/control-components/menu',
          'design/components/control-components/text-selection'],
        },
        {
          type: 'category',
          label: '输入类',
          link: { type: 'doc', id: 'design/components/input-components/index' },
          items: [          'design/components/input-components/text-input',
          'design/components/input-components/search',
          'design/components/input-components/counter',
          'design/components/input-components/pattern-lock'],
        },
        {
          type: 'category',
          label: '选择类',
          link: { type: 'doc', id: 'design/components/selection-components/index' },
          items: [          'design/components/selection-components/checkbox',
          'design/components/selection-components/toggle-switch',
          'design/components/selection-components/radio',
          'design/components/selection-components/rating',
          'design/components/selection-components/slider',
          'design/components/selection-components/picker',
          'design/components/selection-components/segment-button'],
        },
        {
          type: 'category',
          label: '容器类',
          link: { type: 'doc', id: 'design/components/container-components/index' },
          items: [          'design/components/container-components/list',
          'design/components/container-components/dialog',
          'design/components/container-components/bind-sheet'],
        }],
    },
    {
      type: 'category',
      label: '人机交互',
      link: { type: 'doc', id: 'design/hmi/index' },
      items: [        'design/hmi/overview',
        'design/hmi/touchscreen',
        'design/hmi/cursor',
        'design/hmi/focus',
        'design/hmi/mouse',
        'design/hmi/keyboard',
        'design/hmi/touchpad',
        {
          type: 'category',
          label: '常用交互',
          link: { type: 'doc', id: 'design/hmi/scenes/index' },
          items: [          'design/hmi/scenes/drag',
          'design/hmi/scenes/selection'],
        },
        'design/hmi/interaction-events'],
    },
    {
      type: 'category',
      label: '系统特性&能力',
      link: { type: 'doc', id: 'design/system-features/index' },
      items: [        {
          type: 'category',
          label: '系统特性',
          link: { type: 'doc', id: 'design/system-features/features/index' },
          items: [          'design/system-features/features/navigation-bar',
          'design/system-features/features/notification',
          'design/system-features/features/live-view',
          'design/system-features/features/multi-window',
          'design/system-features/features/service-widget',
          'design/system-features/features/pip',
          'design/system-features/features/dark-mode',
          'design/system-features/features/status-bar',
          'design/system-features/features/broadcasting-control'],
        },
        {
          type: 'category',
          label: '系统能力',
          link: { type: 'doc', id: 'design/system-features/capabilities/index' },
          items: [          'design/system-features/capabilities/share',
          'design/system-features/capabilities/huawei-id',
          'design/system-features/capabilities/huawei-pay',
          'design/system-features/capabilities/preview',
          'design/system-features/capabilities/launch-page',
          'design/system-features/capabilities/onehop',
          'design/system-features/capabilities/i-connect',
          'design/system-features/capabilities/smart-reachability'],
        }],
    },
    {
      type: 'category',
      label: '元服务设计',
      link: { type: 'doc', id: 'design/atomic-service-design/index' },
      items: [        'design/atomic-service-design/overview',
        {
          type: 'category',
          label: '元服务基本要素',
          link: { type: 'doc', id: 'design/atomic-service-design/basic-elements/index' },
          items: [          'design/atomic-service-design/basic-elements/basic-info',
          'design/atomic-service-design/basic-elements/service-card'],
        },
        'design/atomic-service-design/experience-scenes',
        {
          type: 'category',
          label: '设计原则',
          link: { type: 'doc', id: 'design/atomic-service-design/design-principles/index' },
          items: [          'design/atomic-service-design/design-principles/universal-friendly',
          'design/atomic-service-design/design-principles/lightweight',
          'design/atomic-service-design/design-principles/concise',
          'design/atomic-service-design/design-principles/secure'],
        },
        {
          type: 'category',
          label: '最佳设计实践',
          link: { type: 'doc', id: 'design/atomic-service-design/best-practices/index' },
          items: [          'design/atomic-service-design/best-practices/accounts'],
        }],
    },
    {
      type: 'category',
      label: '针对多设备设计',
      link: { type: 'doc', id: 'design/multi-device-design/index' },
      items: [        'design/multi-device-design/phone',
        {
          type: 'category',
          label: '折叠屏',
          link: { type: 'doc', id: 'design/multi-device-design/folding-screen/index' },
          items: [          'design/multi-device-design/folding-screen/design-principles',
          'design/multi-device-design/folding-screen/foldable',
          'design/multi-device-design/folding-screen/trifold',
          'design/multi-device-design/folding-screen/flip'],
        },
        'design/multi-device-design/pad',
        {
          type: 'category',
          label: '电脑',
          link: { type: 'doc', id: 'design/multi-device-design/2in1/index' },
          items: [          'design/multi-device-design/2in1/concept',
          'design/multi-device-design/2in1/window',
          'design/multi-device-design/2in1/app-design',
          'design/multi-device-design/2in1/statusbar',
          'design/multi-device-design/2in1/foldable-pc'],
        },
        'design/multi-device-design/smart-cockpit',
        {
          type: 'category',
          label: '智能穿戴',
          link: { type: 'doc', id: 'design/multi-device-design/wearable/index' },
          items: [          'design/multi-device-design/wearable/overview',
          'design/multi-device-design/wearable/application-architecture',
          'design/multi-device-design/wearable/human-machine-interaction',
          'design/multi-device-design/wearable/spacing-parameters'],
        },
        'design/multi-device-design/vision'],
    },
    {
      type: 'category',
      label: '应用设计最佳实践',
      link: { type: 'doc', id: 'design/app-design-practices/index' },
      items: [        'design/app-design-practices/overview',
        'design/app-design-practices/media-entertainment',
        'design/app-design-practices/social-communication',
        'design/app-design-practices/photo-beauty',
        'design/app-design-practices/news-reading',
        'design/app-design-practices/ecommerce',
        'design/app-design-practices/finance',
        'design/app-design-practices/convenient-life',
        'design/app-design-practices/tourist-accommodation',
        'design/app-design-practices/travel-navigation',
        'design/app-design-practices/mobile-payment',
        'design/app-design-practices/games',
        'design/app-design-practices/cars',
        'design/app-design-practices/office'],
    },
    {
      type: 'category',
      label: '应用 UX 体验标准',
      link: { type: 'doc', id: 'design/ux-standards/index' },
      items: [        'design/ux-standards/overview',
        'design/ux-standards/general-ux',
        'design/ux-standards/large-screen-ux',
        'design/ux-standards/foldable-screen-ux',
        'design/ux-standards/2in1-ux',
        'design/ux-standards/vision-ux',
        'design/ux-standards/atomic-service-ux',
        'design/ux-standards/wearable-ux'],
    },
    {
      type: 'category',
      label: '变更说明',
      link: { type: 'doc', id: 'design/changelog/index' },
      items: [        'design/changelog/whats-new'],
    },
  ],
  toolsSidebar: [
    'tools/overview',
    {
      type: 'category',
      label: '开发环境搭建',
      link: { type: 'doc', id: 'tools/setup/index' },
      items: [],
    },
    {
      type: 'category',
      label: '使用AI智能辅助编程',
      link: { type: 'doc', id: 'tools/ai-assist/index' },
      items: [],
    },
    {
      type: 'category',
      label: '编写与调试应用',
      link: { type: 'doc', id: 'tools/coding-debug/index' },
      items: [],
    },
    {
      type: 'category',
      label: '构建应用',
      link: { type: 'doc', id: 'tools/build/index' },
      items: [],
    },
    {
      type: 'category',
      label: '应用测试',
      link: { type: 'doc', id: 'tools/test/index' },
      items: [],
    },
    {
      type: 'category',
      label: '优化应用性能',
      link: { type: 'doc', id: 'tools/optimize/index' },
      items: [],
    },
    {
      type: 'category',
      label: '发布应用',
      link: { type: 'doc', id: 'tools/publish/index' },
      items: [],
    },
    {
      type: 'category',
      label: '命令行工具',
      link: { type: 'doc', id: 'tools/cli-tools/index' },
      items: [],
    },
    {
      type: 'category',
      label: '应用体验建议',
      link: { type: 'doc', id: 'tools/experience/index' },
      items: [],
    },
  ],
   
};

module.exports = sidebars;
