// @ts-check
// Sidebar for dev-app module (app-dev + getting-started + testing + multi-device + ndk-dev + atomic-dev + faq)

const appDevSidebar = require('./sidebars-appdev.js').appDevSidebar;
const atomicSidebar = require('./sidebars-atomic.js').atomicSidebar;

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  gettingStartedSidebar: [
    'dev/getting-started/overview',
  ],
  appDevSidebar,
  multiDeviceSidebar: [
  {
    type: 'category',
    label: '一次开发，多端部署',
    collapsed: true,
    items: [
      'dev/multi-device/bpta-multi-device-overview',
      'dev/multi-device/bpta-multi-device-start',
      'dev/multi-device/bpta-multi-device-design-principles',
      {
        type: 'category',
        label: '多设备界面开发',
        collapsed: true,
        items: [
          {
            type: 'category',
            label: '多设备窗口形态',
            collapsed: true,
            items: [
              'dev/multi-device/bpta-multi-device-window-mode',
              'dev/multi-device/bpta-multi-device-window-direction',
              'dev/multi-device/bpta-multi-device-window-immersive',
            ],
          },
          'dev/multi-device/bpta-multi-device-layout-overview',
          {
            type: 'category',
            label: '界面布局响应式变化',
            collapsed: true,
            items: [
              'dev/multi-device/bpta-multi-device-responsive-layout',
              'dev/multi-device/bpta-multi-device-page-layout',
              'dev/multi-device/bpta-multi-device-component-layout',
              'dev/multi-device/bpta-multi-device-screen-layout',
            ],
          },
          {
            type: 'category',
            label: '界面元素自适应变化',
            collapsed: true,
            items: [
              'dev/multi-device/bpta-multi-device-adaptive-layout',
            ],
          },
          {
            type: 'category',
            label: '特殊界面布局场景',
            collapsed: true,
            items: [
              'dev/multi-device/bpta-folded-hover',
              'dev/multi-device/bpta-web-adaptation',
            ],
          },
          {
            type: 'category',
            label: '多设备交互',
            collapsed: true,
            items: [
              'dev/multi-device/bpta-multi-interaction',
            ],
          },
          'dev/multi-device/bpta-multi-device-resource',
          {
            type: 'category',
            label: '多设备界面开发案例',
            collapsed: true,
            items: [
              'dev/multi-device/multi-video-app',
              'dev/multi-device/multi-ticket-class',
              'dev/multi-device/multi-business-office',
              'dev/multi-device/bpta-multi-music-app-overview',
              'dev/multi-device/multi-shopping-price-comparison',
              'dev/multi-device/multi-travel-accommodation',
              'dev/multi-device/multi-travel-navigation',
              'dev/multi-device/multi-convenient-life',
              'dev/multi-device/multi-financial-app',
              'dev/multi-device/multi-community-app',
              'dev/multi-device/multi-news-read',
              'dev/multi-device/multi-mobile-payment',
              'dev/multi-device/multi-communication-app',
              'dev/multi-device/multi-picture-app',
              'dev/multi-device/bpta-multi_game',
              'dev/multi-device/bpta-multi-settings-application-page',
              'dev/multi-device/multi-short-video-app',
            ],
          },
        ],
      },
      {
        type: 'category',
        label: '多设备功能开发',
        collapsed: true,
        items: [
          'dev/multi-device/bpta-multi-device-function',
          'dev/multi-device/bpta-multi-device-camera',
          'dev/multi-device/bpta-multi-device-screen-diff',
        ],
      },
      'dev/multi-device/bpta-multi-device-ide',
    ],
  },
  {
    type: 'category',
    label: '自由流转',
    collapsed: true,
    items: [
      'dev/multi-device/bpta-hopping',
      {
        type: 'category',
        label: '跨端迁移',
        collapsed: true,
        items: [
          'dev/multi-device/bpta-continue-cast',
          'dev/multi-device/bpta-continue-data',
          'dev/multi-device/bpta-application-continue-progess',
        ],
      },
      {
        type: 'category',
        label: '多端协同',
        collapsed: true,
        items: [
          'dev/multi-device/bpta-vdeocast',
          'dev/multi-device/bpta-audio-cast',
          'dev/multi-device/bpta-distribute-drag-cast',
          'dev/multi-device/bpta-unified-drag-and-drop',
          'dev/multi-device/bpta-distributed-pasteboard-cast',
          'dev/multi-device/bpta-distributed-pasteboard',
          'dev/multi-device/bpta-application-knock-video-share',
          'dev/multi-device/bpta-application-knock-file-share',
          'dev/multi-device/bpta-application-gesture-share',
        ],
      },
      {
        type: 'category',
        label: '典型全场景协同开发案例',
        collapsed: true,
        items: [
          'dev/multi-device/bpta-collaboration-office',
          'dev/multi-device/bpta-smartwatchnavigation',
          'dev/multi-device/bpta-continue',
        ],
      },
    ],
  },
  {
    type: 'category',
    label: '多端设备体验提升',
    collapsed: true,
    items: [
      {
        type: 'category',
        label: '手机',
        collapsed: true,
        items: [
          'dev/multi-device/bpta-foldable-guide',
          'dev/multi-device/bpta-purax-guide',
          'dev/multi-device/bpta-matext-guide',
        ],
      },
      {
        type: 'category',
        label: '平板',
        collapsed: true,
        items: [
          'dev/multi-device/bpta-pad-guide',
        ],
      },
      {
        type: 'category',
        label: '电脑',
        collapsed: true,
        items: [
          'dev/multi-device/bpta-pc-guide',
          'dev/multi-device/bpta-mate-book-fold',
        ],
      },
      {
        type: 'category',
        label: '穿戴',
        collapsed: true,
        items: [
          'dev/multi-device/bpta-smartwatch',
          'dev/multi-device/bpta-lite-wearable-guide',
        ],
      },
      {
        type: 'category',
        label: '智慧屏',
        collapsed: true,
        items: [
          'dev/multi-device/bpta-matetv-guide',
        ],
      },
    ],
  },
],
  atomicDevSidebar: atomicSidebar,
  ndkDevSidebar: [
    'dev/ndk-dev/ndk-development-overview',
    'dev/ndk-dev/create-with-ndk',
    {
      type: 'category',
      label: '构建NDK工程',
      collapsed: true,
      items: [
        'dev/ndk-dev/build-with-ndk-overview',
        'dev/ndk-dev/build-with-ndk-ide',
        'dev/ndk-dev/build-with-ndk-cmake',
        'dev/ndk-dev/build-with-ndk-prebuilts',
        'dev/ndk-dev/bisheng-compiler',
      ],
    },
    {
      type: 'category',
      label: '代码开发',
      collapsed: true,
      items: [
        'dev/ndk-dev/develop-code-overview',
        {
          type: 'category',
          label: 'C/C++标准库',
          collapsed: true,
          items: [
            'dev/ndk-dev/c-cpp-overview',
            'dev/ndk-dev/fdsan',
          ],
        },
        {
          type: 'category',
          label: '使用Node-API实现ArkTS/JS与C/C++语言交互',
          collapsed: true,
          items: [
            'dev/ndk-dev/napi-introduction',
            'dev/ndk-dev/napi_status_introduction',
            'dev/ndk-dev/napi-data-types-interfaces',
            'dev/ndk-dev/napi-guidelines',
            'dev/ndk-dev/use-napi-process',
            {
              type: 'category',
              label: 'Node-API使用指导',
              collapsed: true,
              items: [
                'dev/ndk-dev/use-napi-about-extension',
                'dev/ndk-dev/use-napi-about-array',
                'dev/ndk-dev/use-napi-about-arraybuffer',
                'dev/ndk-dev/use-napi-about-bigint',
                'dev/ndk-dev/use-napi-about-buffer',
                'dev/ndk-dev/use-napi-basic-data-types',
                'dev/ndk-dev/use-napi-about-class',
                'dev/ndk-dev/use-napi-about-cleanuphook',
                'dev/ndk-dev/use-napi-about-date',
                'dev/ndk-dev/use-napi-about-error',
                'dev/ndk-dev/use-napi-about-environmental-life-cycle',
                'dev/ndk-dev/use-napi-about-function',
                'dev/ndk-dev/use-napi-life-cycle',
                'dev/ndk-dev/use-napi-about-object',
                'dev/ndk-dev/use-napi-about-other-practical-tools',
                'dev/ndk-dev/use-napi-about-primitive',
                'dev/ndk-dev/use-napi-about-promise',
                'dev/ndk-dev/use-napi-about-property',
                'dev/ndk-dev/use-napi-about-string',
                'dev/ndk-dev/use-napi-about-custom-asynchronous-operations',
              ],
            },
            {
              type: 'category',
              label: 'Node-API典型使用场景',
              collapsed: true,
              items: [
                'dev/ndk-dev/use-napi-asynchronous-task',
                'dev/ndk-dev/use-napi-thread-safety',
                'dev/ndk-dev/use-napi-object-wrap',
                'dev/ndk-dev/use-sendable-napi',
                'dev/ndk-dev/use-napi-ark-runtime',
                'dev/ndk-dev/use-napi-load-module',
                'dev/ndk-dev/use-napi-event-loop',
                'dev/ndk-dev/use-napi-load-module-with-info',
                'dev/ndk-dev/use-call-threadsafe-function-with-priority',
                'dev/ndk-dev/use-napi-about-context',
                'dev/ndk-dev/use-napi-about-strong-reference',
                'dev/ndk-dev/use-napi-about-critical',
                'dev/ndk-dev/use-napi-about-crash',
                'dev/ndk-dev/use-napi-method-promise',
                'dev/ndk-dev/use-napi-about-sendable-reference',
              ],
            },
            {
              type: 'category',
              label: 'Node-API常见问题汇总',
              collapsed: true,
              items: [
                'dev/ndk-dev/use-napi-faqs',
                'dev/ndk-dev/napi-faq-about-stability',
                'dev/ndk-dev/napi-faq-about-memory-leak',
                'dev/ndk-dev/napi-faq-about-common-basic',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '使用JSVM-API实现JS与C/C++语言交互',
          collapsed: true,
          items: [
            'dev/ndk-dev/jsvm-introduction',
            'dev/ndk-dev/jsvm-data-types-interfaces',
            'dev/ndk-dev/use-jsvm-process',
            {
              type: 'category',
              label: 'JSVM-API开发规范',
              collapsed: true,
              items: [
                'dev/ndk-dev/jsvm-guidelines',
                'dev/ndk-dev/jsvm-frequently-questions',
              ],
            },
            {
              type: 'category',
              label: 'JSVM-API使用指导',
              collapsed: true,
              items: [
                'dev/ndk-dev/use-jsvm-execute_tasks',
                'dev/ndk-dev/use-jsvm-create-snapshot',
                'dev/ndk-dev/use-jsvm-about-wasm',
                'dev/ndk-dev/use-jsvm-function-call',
                'dev/ndk-dev/use-jsvm-about-json',
                'dev/ndk-dev/use-jsvm-about-array',
                'dev/ndk-dev/use-jsvm-about-arraybuffer',
                'dev/ndk-dev/use-jsvm-about-bigint',
                'dev/ndk-dev/use-jsvm-about-class',
                'dev/ndk-dev/use-jsvm-about-date',
                'dev/ndk-dev/use-jsvm-about-debug-option',
                'dev/ndk-dev/use-jsvm-about-object',
                'dev/ndk-dev/use-jsvm-about-primitive',
                'dev/ndk-dev/use-jsvm-about-promise',
                'dev/ndk-dev/use-jsvm-about-property',
                'dev/ndk-dev/use-jsvm-about-string',
                'dev/ndk-dev/use-jsvm-about-version',
                'dev/ndk-dev/use-jsvm-error',
                'dev/ndk-dev/m-heapstatistics-debugger-cpuprofiler-heapsnapshot',
                'dev/ndk-dev/use-jsvm-life-cycle',
                'dev/ndk-dev/use-jsvm-memory-management',
                'dev/ndk-dev/use-jsvm-strict-equals',
                'dev/ndk-dev/use-jsvm-trigger-exceptions',
                'dev/ndk-dev/use-jsvm-trigger-gc',
                'dev/ndk-dev/use-jsvm-about-private',
                'dev/ndk-dev/use-jsvm-about-external-string',
                'dev/ndk-dev/use-jsvm-about-proxy',
                'dev/ndk-dev/use-jsvm-about-well-known-symbols',
                'dev/ndk-dev/use-jsvm-about-wrapper-object',
                'dev/ndk-dev/use-jsvm-basic-data-types',
              ],
            },
            {
              type: 'category',
              label: 'JSVM-API典型使用场景指导',
              collapsed: true,
              items: [
                'dev/ndk-dev/jsvm-debugger-cpuprofiler-heapsnapshot',
                'dev/ndk-dev/use-jsvm-about-trace',
                'dev/ndk-dev/jsvm-apply-jit-profile',
                'dev/ndk-dev/jsvm-secure-shield-mode',
                'dev/ndk-dev/jsvm-locate-memory-leak',
                {
                  type: 'category',
                  label: 'JSVM-API调优&高性能使用示例',
                  collapsed: true,
                  items: [
                    'dev/ndk-dev/use-jsvm-runtime-task',
                    'dev/ndk-dev/use-jsvm-about-code-cache',
                    'dev/ndk-dev/jsvm-optimizations',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'JSVM性能调试指导',
              collapsed: true,
              items: [
                'dev/ndk-dev/use-jsvm-about-v8-trace',
                'dev/ndk-dev/use-jsvm-about-analyze-memory-usage',
              ],
            },
          ],
        },
        'dev/ndk-dev/use-longque-js-api',
        {
          type: 'category',
          label: 'OpenMP支持',
          collapsed: true,
          items: [
            'dev/ndk-dev/openmp-overview',
            'dev/ndk-dev/openmp-guideline',
          ],
        },
        'dev/ndk-dev/rawfile-guidelines',
        {
          type: 'category',
          label: '线程调度',
          collapsed: true,
          items: [
            'dev/ndk-dev/qos-guidelines',
            'dev/ndk-dev/gewu-ndk-api-guidelines',
          ],
        },
        'dev/ndk-dev/purgeable-memory-guidelines',
        'dev/ndk-dev/native-bundle-guidelines',
      ],
    },
    {
      type: 'category',
      label: '编译工具链',
      collapsed: true,
      items: [
        'dev/ndk-dev/toolchain-gn-build-project',
        'dev/ndk-dev/toolchain-cmake-build-project',
        'dev/ndk-dev/toolchain-make-build-project',
        'dev/ndk-dev/toolchain-configure-build-project',
        'dev/ndk-dev/toolchain-lycium-build-project',
      ],
    },
    {
      type: 'category',
      label: '调试和性能分析',
      collapsed: true,
      items: [
        'dev/ndk-dev/debug-performance-profiling-overview',
        'dev/ndk-dev/debug-asan',
        'dev/ndk-dev/debug-lldb',
      ],
    },
    {
      type: 'category',
      label: '硬件兼容性',
      collapsed: true,
      items: [
        'dev/ndk-dev/hw-guide',
        'dev/ndk-dev/ohos-abi',
        'dev/ndk-dev/cpu-features',
        'dev/ndk-dev/neon-guide',
      ],
    },
  ],
  testingSidebar: [
    'dev/testing/overview',
  ],
  devFaqSidebar: [
    'dev/faq/overview',
  ],
};

module.exports = sidebars;
