// @ts-check
// Sidebar for design module

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  designSidebar: [
    {
      type: 'category',
      label: '通用设计基础',
      link: { type: 'doc', id: 'design/general-design-basics/index' },
      items: [        'design/general-design-basics/design-concepts',
        {
          type: 'category',
          label: '视觉风格',
          link: { type: 'doc', id: 'design/general-design-basics/visual-design/index' },
          items: [          'design/general-design-basics/visual-design/color',
          'design/general-design-basics/visual-design/font',
          'design/general-design-basics/visual-design/app-icon',
          'design/general-design-basics/visual-design/harmonyos-symbol'],
        },
        {
          type: 'category',
          label: '布局',
          link: { type: 'doc', id: 'design/general-design-basics/layout/index' },
          items: [          'design/general-design-basics/layout/layout-basics',
          'design/general-design-basics/layout/responsive-structure',
          'design/general-design-basics/layout/responsive-method'],
        },
        {
          type: 'category',
          label: '动效',
          link: { type: 'doc', id: 'design/general-design-basics/animation/index' },
          items: [          'design/general-design-basics/animation/overview',
          'design/general-design-basics/animation/principles',
          'design/general-design-basics/animation/attributes',
          'design/general-design-basics/animation/transition',
          'design/general-design-basics/animation/gesture'],
        },
        'design/general-design-basics/ui-language',
        'design/general-design-basics/globalization',
        'design/general-design-basics/privacy'],
    },
    {
      type: 'category',
      label: '控件',
      link: { type: 'doc', id: 'design/components/index' },
      items: [        'design/components/overview',
        {
          type: 'category',
          label: '导航类',
          link: { type: 'doc', id: 'design/components/navigation/index' },
          items: [          'design/components/navigation/bottom-tab',
          'design/components/navigation/chips-group',
          'design/components/navigation/title-bar',
          'design/components/navigation/swiper'],
        },
        {
          type: 'category',
          label: '展示类',
          link: { type: 'doc', id: 'design/components/view-components/index' },
          items: [          'design/components/view-components/text',
          'design/components/view-components/divider',
          'design/components/view-components/subheader',
          'design/components/view-components/progress',
          'design/components/view-components/alphabet-indexer',
          'design/components/view-components/scrollbar',
          'design/components/view-components/badge',
          'design/components/view-components/toast',
          'design/components/view-components/snackbar',
          'design/components/view-components/popup',
          'design/components/view-components/data-panel',
          'design/components/view-components/qrcode',
          'design/components/view-components/textclock',
          'design/components/view-components/image',
          'design/components/view-components/blank'],
        },
        {
          type: 'category',
          label: '操作类',
          link: { type: 'doc', id: 'design/components/control-components/index' },
          items: [          'design/components/control-components/button',
          'design/components/control-components/select',
          'design/components/control-components/toggle-button',
          'design/components/control-components/chips',
          'design/components/control-components/toolbar',
          'design/components/control-components/action-bar',
          'design/components/control-components/menu',
          'design/components/control-components/text-selection'],
        },
        {
          type: 'category',
          label: '输入类',
          link: { type: 'doc', id: 'design/components/input-components/index' },
          items: [          'design/components/input-components/text-input',
          'design/components/input-components/search',
          'design/components/input-components/counter',
          'design/components/input-components/pattern-lock'],
        },
        {
          type: 'category',
          label: '选择类',
          link: { type: 'doc', id: 'design/components/selection-components/index' },
          items: [          'design/components/selection-components/checkbox',
          'design/components/selection-components/toggle-switch',
          'design/components/selection-components/radio',
          'design/components/selection-components/rating',
          'design/components/selection-components/slider',
          'design/components/selection-components/picker',
          'design/components/selection-components/segment-button'],
        },
        {
          type: 'category',
          label: '容器类',
          link: { type: 'doc', id: 'design/components/container-components/index' },
          items: [          'design/components/container-components/list',
          'design/components/container-components/dialog',
          'design/components/container-components/bind-sheet'],
        }],
    },
    {
      type: 'category',
      label: '人机交互',
      link: { type: 'doc', id: 'design/hmi/index' },
      items: [        'design/hmi/overview',
        'design/hmi/touchscreen',
        'design/hmi/cursor',
        'design/hmi/focus',
        'design/hmi/mouse',
        'design/hmi/keyboard',
        'design/hmi/touchpad',
        {
          type: 'category',
          label: '常用交互',
          link: { type: 'doc', id: 'design/hmi/scenes/index' },
          items: [          'design/hmi/scenes/drag',
          'design/hmi/scenes/selection'],
        },
        'design/hmi/interaction-events'],
    },
    {
      type: 'category',
      label: '系统特性&能力',
      link: { type: 'doc', id: 'design/system-features/index' },
      items: [        {
          type: 'category',
          label: '系统特性',
          link: { type: 'doc', id: 'design/system-features/features/index' },
          items: [          'design/system-features/features/navigation-bar',
          'design/system-features/features/notification',
          'design/system-features/features/live-view',
          'design/system-features/features/multi-window',
          'design/system-features/features/service-widget',
          'design/system-features/features/pip',
          'design/system-features/features/dark-mode',
          'design/system-features/features/status-bar',
          'design/system-features/features/broadcasting-control'],
        },
        {
          type: 'category',
          label: '系统能力',
          link: { type: 'doc', id: 'design/system-features/capabilities/index' },
          items: [          'design/system-features/capabilities/share',
          'design/system-features/capabilities/huawei-id',
          'design/system-features/capabilities/huawei-pay',
          'design/system-features/capabilities/preview',
          'design/system-features/capabilities/launch-page',
          'design/system-features/capabilities/onehop',
          'design/system-features/capabilities/i-connect',
          'design/system-features/capabilities/smart-reachability'],
        }],
    },
    {
      type: 'category',
      label: '元服务设计',
      link: { type: 'doc', id: 'design/atomic-service-design/index' },
      items: [        'design/atomic-service-design/overview',
        {
          type: 'category',
          label: '元服务基本要素',
          link: { type: 'doc', id: 'design/atomic-service-design/basic-elements/index' },
          items: [          'design/atomic-service-design/basic-elements/basic-info',
          'design/atomic-service-design/basic-elements/service-card'],
        },
        'design/atomic-service-design/experience-scenes',
        {
          type: 'category',
          label: '设计原则',
          link: { type: 'doc', id: 'design/atomic-service-design/design-principles/index' },
          items: [          'design/atomic-service-design/design-principles/universal-friendly',
          'design/atomic-service-design/design-principles/lightweight',
          'design/atomic-service-design/design-principles/concise',
          'design/atomic-service-design/design-principles/secure'],
        },
        {
          type: 'category',
          label: '最佳设计实践',
          link: { type: 'doc', id: 'design/atomic-service-design/best-practices/index' },
          items: [          'design/atomic-service-design/best-practices/accounts'],
        }],
    },
    {
      type: 'category',
      label: '针对多设备设计',
      link: { type: 'doc', id: 'design/multi-device-design/index' },
      items: [        'design/multi-device-design/phone',
        {
          type: 'category',
          label: '折叠屏',
          link: { type: 'doc', id: 'design/multi-device-design/folding-screen/index' },
          items: [          'design/multi-device-design/folding-screen/design-principles',
          'design/multi-device-design/folding-screen/foldable',
          'design/multi-device-design/folding-screen/trifold',
          'design/multi-device-design/folding-screen/flip'],
        },
        'design/multi-device-design/pad',
        {
          type: 'category',
          label: '电脑',
          link: { type: 'doc', id: 'design/multi-device-design/2in1/index' },
          items: [          'design/multi-device-design/2in1/concept',
          'design/multi-device-design/2in1/window',
          'design/multi-device-design/2in1/app-design',
          'design/multi-device-design/2in1/statusbar',
          'design/multi-device-design/2in1/foldable-pc'],
        },
        'design/multi-device-design/smart-cockpit',
        {
          type: 'category',
          label: '智能穿戴',
          link: { type: 'doc', id: 'design/multi-device-design/wearable/index' },
          items: [          'design/multi-device-design/wearable/overview',
          'design/multi-device-design/wearable/application-architecture',
          'design/multi-device-design/wearable/human-machine-interaction',
          'design/multi-device-design/wearable/spacing-parameters'],
        },
        'design/multi-device-design/vision'],
    },
    {
      type: 'category',
      label: '应用设计最佳实践',
      link: { type: 'doc', id: 'design/app-design-practices/index' },
      items: [        'design/app-design-practices/overview',
        'design/app-design-practices/media-entertainment',
        'design/app-design-practices/social-communication',
        'design/app-design-practices/photo-beauty',
        'design/app-design-practices/news-reading',
        'design/app-design-practices/ecommerce',
        'design/app-design-practices/finance',
        'design/app-design-practices/convenient-life',
        'design/app-design-practices/tourist-accommodation',
        'design/app-design-practices/travel-navigation',
        'design/app-design-practices/mobile-payment',
        'design/app-design-practices/games',
        'design/app-design-practices/cars',
        'design/app-design-practices/office'],
    },
    {
      type: 'category',
      label: '应用 UX 体验标准',
      link: { type: 'doc', id: 'design/ux-standards/index' },
      items: [        'design/ux-standards/overview',
        'design/ux-standards/general-ux',
        'design/ux-standards/large-screen-ux',
        'design/ux-standards/foldable-screen-ux',
        'design/ux-standards/2in1-ux',
        'design/ux-standards/vision-ux',
        'design/ux-standards/atomic-service-ux',
        'design/ux-standards/wearable-ux'],
    },
    {
      type: 'category',
      label: '变更说明',
      link: { type: 'doc', id: 'design/changelog/index' },
      items: [        'design/changelog/whats-new'],
    },
  ],
};

module.exports = sidebars;
